#include "GUI\Login.au3"
#include "GUI\forms\Options Form.au3"
#include "GUI\forms\About Form.au3"

#include "Attack\dropCC.au3"
#include "Attack\dropHeroes.au3"
#include "Attack\GoldElixirChange.au3"
#include "Attack\PrepareAttack.au3"
#include "Attack\ReturnHome.au3"
#include "Attack\NameOfTroop.au3"
#include "Attack\SpellDarkStorage.au3"
#include "Attack\Attack Algorithms\algorithmTH.au3"
#include "Attack\Attack Algorithms\algorithm_AllTroops.au3"
#include "Attack\Attack Algorithms\algorithm_Barch.au3"

#include "Config\applyConfig.au3"
#include "Config\readConfig.au3"
#include "Config\saveConfig.au3"
#include "Config\ScreenCoordinates.au3"
#include "Config\saveloadConfig.au3"

#include "Image Search\ImageSearch.au3"
#include "Image Search\checkDeadBase.au3"
#include "Image Search\checkTownhall.au3"
#include "Image Search\checkWall.au3"
#include "Image Search\checkDarkElix.au3"
#include "Image Search\checkDefense.au3"

#include "Main Screen\checkMainScreen.au3"
#include "Main Screen\checkObstacles.au3"
#include "Main Screen\waitMainScreen.au3"
#include "Main Screen\ZoomOut.au3"

#include "Other\_Sleep.au3"
#include "Other\Click.au3"
#include "Other\CreateLogFile.au3"
#include "Other\FindPos.au3"
#include "Other\getBSPos.au3"
#include "Other\SetLog.au3"
#include "Other\Tab.au3"
#include "Other\Time.au3"
#include "Other\BlockInputEx.au3"
#include "Other\_NumberFormat.au3"
#include "Other\stuckHandler.au3"
#include "Other\divideDigit.au3"
#include "Other\RandomGaussian.au3"

#include "Pixels\_CaptureRegion.au3"
#include "Pixels\_ColorCheck.au3"
#include "Pixels\_GetPixelColor.au3"
#include "Pixels\_PixelSearch.au3"
#include "Pixels\_MultiPixelSearch.au3"
#include "Pixels\_WaitForPixel.au3"
#include "Pixels\boolPixelSearch.au3"

#include "Read Text\getChar.au3"
#include "Read Text\getDarkElixir.au3"
#include "Read Text\getDigit.au3"
#include "Read Text\getDigitLarge.au3"
#include "Read Text\getDigitSmall.au3"
#include "Read Text\getElixir.au3"
#include "Read Text\getGold.au3"
#include "Read Text\getNormal.au3"
#include "Read Text\getOther.au3"
#include "Read Text\getTrophy.au3"
#include "Read Text\getString.au3"
#include "Read Text\getDigitTownHall.au3"
#include "Read Text\getDigitLastRaid.au3"
#include "Read Text\getDigitTrainTroops.au3"

#include "Search\checkNextButton.au3"
#include "Search\CompareResources.au3"
#include "Search\GetResources.au3"
#include "Search\PrepareSearch.au3"
#include "Search\VillageSearch.au3"

#include "Village\BoostAllBuilding.au3"
#include "Village\CheckFullArmy.au3"
#include "Village\CheckArmyCamp.au3"
#include "Village\Collect.au3"
#include "Village\DonateCC.au3"
#include "Village\DropTrophy.au3"
#include "Village\isGoldFull.au3"
#include "Village\isElixirFull.au3"
#include "Village\LocateBuildings.au3"
#include "Village\ReArm.au3"
#include "Village\RequestCC.au3"
#include "Village\Train.au3"
#include "Village\BotCommand.au3"
#include "Village\UpgradeWall.au3"
#include "Village\UpgradeBuilding.au3"
#include "Village\VillageReport.au3"
#include "Village\CreateSpell.au3"
#include "Village\TrainDark.au3"
#include "Village\TrainCustom.au3"
#include "Village\CheckCostPerSearch.au3"

#include "Notification\PushBullet.au3"
