#include <ButtonConstants.au3>
#include <ComboConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <TabConstants.au3>
#include <WindowsConstants.au3>
#Region ### START Koda GUI section ### Form=c:\users\admin\desktop\cb\trunk\scripts\gui\forms\gui form.kxf
$frmBot = GUICreate("sBotTitle", 647, 432, -1, -1)
$menuFile = GUICtrlCreateMenu("&File")
$menuItemExit = GUICtrlCreateMenuItem("Exit"&@TAB&"PgUp", $menuFile)
$menuConfig = GUICtrlCreateMenu("&Config")
$menuItemLoad = GUICtrlCreateMenuItem("Load"&@TAB&"", $menuConfig)
$menuItemSave = GUICtrlCreateMenuItem("Save", $menuConfig)
$menuItemTheme = GUICtrlCreateMenu("&Themes")
$menuItemNone = GUICtrlCreateMenuItem("None"&@TAB&"", $menuItemTheme)
$menuItemDefault = GUICtrlCreateMenuItem("Default"&@TAB&"Caps Lock", $menuItemTheme)
$menuItemIron = GUICtrlCreateMenuItem("Iron"&@TAB&"", $menuItemTheme)
$menuItemSteel = GUICtrlCreateMenuItem("Steel", $menuItemTheme)
$menuItemGray = GUICtrlCreateMenuItem("Gray"&@TAB&"", $menuItemTheme)
$menuItemDark = GUICtrlCreateMenuItem("Dark", $menuItemTheme)
$menuItemBlack = GUICtrlCreateMenuItem("Black", $menuItemTheme)
$menuItemAlloy = GUICtrlCreateMenuItem("Alloy", $menuItemTheme)
$menuItemHex = GUICtrlCreateMenuItem("Hex"&@TAB&"", $menuItemTheme)
$menuItemCore = GUICtrlCreateMenuItem("Core"&@TAB&"", $menuItemTheme)
$menuItemFresco = GUICtrlCreateMenuItem("Fresco", $menuItemTheme)
$menuItemTeal = GUICtrlCreateMenuItem("Teal", $menuItemTheme)
$menuItemSoft = GUICtrlCreateMenuItem("Soft", $menuItemTheme)
$menuItemGreen = GUICtrlCreateMenuItem("Green"&@TAB&"F5", $menuItemTheme)
$menuItemOrange = GUICtrlCreateMenuItem("Orange", $menuItemTheme)
$menuItemRed = GUICtrlCreateMenuItem("Red", $menuItemTheme)
$menuLanguage = GUICtrlCreateMenu("&Language")
$lngArabic = GUICtrlCreateMenuItem("&Arabic", $menuLanguage)
$lngDeutsch = GUICtrlCreateMenuItem("&Deutsch", $menuLanguage)
$lngEnglish = GUICtrlCreateMenuItem("&English", $menuLanguage)
$lngFilipino = GUICtrlCreateMenuItem("&Filipino", $menuLanguage)
$lngFrench = GUICtrlCreateMenuItem("&French", $menuLanguage)
$lngPortuguese = GUICtrlCreateMenuItem("&Portuguese", $menuLanguage)
$lngSpanish = GUICtrlCreateMenuItem("&Spanish", $menuLanguage)
$lngTurkish = GUICtrlCreateMenuItem("&Turkish", $menuLanguage)
$lngVietnamese = GUICtrlCreateMenuItem("&Vietnamese", $menuLanguage)
$menuHelp = GUICtrlCreateMenu("&Help")
$menuItemAbout = GUICtrlCreateMenuItem("About"&@TAB&"", $menuHelp)
$tabMain = GUICtrlCreateTab(-1, 30, 645, 355)
$pageGeneral = GUICtrlCreateTabItem("General")
$groupLocationSettings = GUICtrlCreateGroup("Locate Buildings Manually", 484, 62, 140, 248)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$btnLocateTownHall = GUICtrlCreateButton("Locate Townhall", 499, 82, 110, 25)
$btnLocateClanCastle2 = GUICtrlCreateButton("Locate Clan Castle", 499, 110, 110, 25)
$btnLocateKingAltar = GUICtrlCreateButton("Locate King Altar", 499, 222, 110, 25)
$btnLocateQueenAltar = GUICtrlCreateButton("Locate Queen Altar", 499, 250, 110, 25)
$btnLocateDarkBarracks = GUICtrlCreateButton("Locate Dark Barrack", 499, 194, 110, 25)
$btnLocateBarracks = GUICtrlCreateButton("Locate Barracks", 499, 166, 110, 25)
$btnLocateSFactory = GUICtrlCreateButton("Locate Spell Factory", 499, 278, 110, 25)
$btnLocateCamp = GUICtrlCreateButton("Locate Army Camp", 499, 138, 110, 25)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupBottomOptions = GUICtrlCreateGroup("Options", 7, 252, 470, 43)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkBotStop = GUICtrlCreateCheckbox("", 22, 271, 16, 16)
$cmbBotCommand = GUICtrlCreateCombo("", 57, 267, 180, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Halt Attack Mode|Shutdown PC|Sleep PC")
$lblPC = GUICtrlCreateLabel("IF :", 252, 270, 16, 17)
$cmbBotCond = GUICtrlCreateCombo("", 287, 267, 180, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "G and E Full and Max.Trophy|(G and E) Full or Max.Trophy|(G or E) Full and Max.Trophy|G or E Full or Max.Trophy|Gold and Elixir Full|Gold or Elixir Full|Gold Full and Max.Trophy|Elixir Full and Max.Trophy|Gold Full or Max.Trophy|Elixir Full or Max.Trophy|Gold Full|Elixir Full|Reach Max. Trophy")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupOtherOptions = GUICtrlCreateGroup("Other Options", 400, 311, 224, 60)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblMaxTrophy = GUICtrlCreateLabel("Trophy Range:", 415, 328, 72, 17)
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$txtMinimumTrophy = GUICtrlCreateInput("1800", 490, 324, 50, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$lblMaxTrophy2 = GUICtrlCreateLabel("-", 550, 328, 5, 17)
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$txtMaxTrophy = GUICtrlCreateInput("2000", 565, 324, 50, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$chkDonateOnly = GUICtrlCreateCheckbox("Donate Only", 532, 348, 80, 17)
GUICtrlSetTip(-1, "Disable attacking  training, only do collections/donating")
$chkNoAttack = GUICtrlCreateCheckbox("Donate/Train Only", 415, 348, 105, 17)
GUICtrlSetTip(-1, "Disable attacking, only do collections/training/donating")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageSearchSetting = GUICtrlCreateTabItem("Search")
$groupDeadConditions = GUICtrlCreateGroup("Dead Base Conditions", 24, 63, 250, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblDeadConditions = GUICtrlCreateLabel("Selected conditions must ALL be met when", 39, 86, 220, 15, $SS_CENTER)
$chkDeadGE = GUICtrlCreateCheckbox("Min Resources:", 39, 130, 100, 17)
$lblDeadMinGold = GUICtrlCreateLabel("Gold:", 144, 132, 28, 17)
$txtDeadMinGold = GUICtrlCreateInput("50000", 179, 128, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$cmbDead = GUICtrlCreateCombo("", 84, 153, 45, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "And|Or")
$lblDeadMinElixir = GUICtrlCreateLabel("Elixir:", 144, 157, 28, 17)
$txtDeadMinElixir = GUICtrlCreateInput("50000", 179, 153, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkDeadMeetDE = GUICtrlCreateCheckbox("Min Dark Elixir:", 39, 180, 95, 17)
$txtDeadMinDarkElixir = GUICtrlCreateInput("0", 179, 178, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkDeadMeetTH = GUICtrlCreateCheckbox("Max TH Level:", 39, 230, 95, 17)
$cmbDeadTH = GUICtrlCreateCombo("", 179, 228, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "4-6|7|8|9|10")
$chkDeadMeetTrophy = GUICtrlCreateCheckbox("Min Trophies:", 39, 205, 85, 17)
$txtDeadMinTrophy = GUICtrlCreateInput("0", 179, 203, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkDeadMeetTHO = GUICtrlCreateCheckbox("Townhall Outside", 39, 255, 100, 17)
$lblDeadConditions2 = GUICtrlCreateLabel("search base with full collectors", 39, 103, 220, 15, $SS_CENTER)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupAnyConditions = GUICtrlCreateGroup("Any Base Conditions", 309, 63, 250, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblAnyConditions = GUICtrlCreateLabel("Selected conditions must ALL be met when", 324, 86, 220, 15, $SS_CENTER)
$chkMeetGE = GUICtrlCreateCheckbox("Min Resources:", 324, 130, 100, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
$lblMinGold = GUICtrlCreateLabel("Gold:", 429, 132, 28, 17)
$txtMinGold = GUICtrlCreateInput("80000", 464, 128, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$cmbAny = GUICtrlCreateCombo("", 369, 153, 45, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "And|Or")
$lblMinElixir = GUICtrlCreateLabel("Elixir:", 429, 157, 28, 17)
$txtMinElixir = GUICtrlCreateInput("80000", 464, 153, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkMeetDE = GUICtrlCreateCheckbox("Min Dark Elixir:", 324, 180, 95, 17)
$txtMinDarkElixir = GUICtrlCreateInput("0", 464, 178, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkMeetTH = GUICtrlCreateCheckbox("Max TH Level:", 324, 230, 95, 17)
$cmbTH = GUICtrlCreateCombo("", 464, 228, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "4-6|7|8|9|10")
$chkMeetTrophy = GUICtrlCreateCheckbox("Min Trophies:", 324, 205, 85, 17)
$txtMinTrophy = GUICtrlCreateInput("0", 464, 203, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkMeetTHO = GUICtrlCreateCheckbox("Townhall Outside", 324, 255, 100, 17)
$lblAnyConditions2 = GUICtrlCreateLabel("search for any other base", 324, 103, 220, 15, $SS_CENTER)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupSearchOnly = GUICtrlCreateGroup("Search Only", 302, 296, 320, 75)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$btnSearchMode = GUICtrlCreateButton("Search Mode", 311, 334, 300, 30)
GUICtrlSetTip(-1, "Does not attack. Searches for base that meets conditions.")
$lblSearchOnly = GUICtrlCreateLabel("Searching only! Disables attacking!", 382, 314, 170, 18)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageAdvanceSetting = GUICtrlCreateTabItem("Adv Search")
$groupRedDead = GUICtrlCreateGroup("Dead Base Search Reduction", 9, 67, 200, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblGoldRedDead = GUICtrlCreateLabel("Gold Reduce:", 19, 142, 70, 17)
$lblElixRedDead = GUICtrlCreateLabel("Elixir Reduce:", 19, 167, 70, 17)
$lblDERedDead = GUICtrlCreateLabel("DE Reduce:", 19, 192, 85, 17)
$lblTroRedDead = GUICtrlCreateLabel("Trophy Reduce:", 19, 217, 85, 17)
$lblRedSearchDead = GUICtrlCreateLabel("After Search:", 19, 242, 80, 17)
$txtGoldRedDead = GUICtrlCreateInput("5000", 139, 139, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtElixRedDead = GUICtrlCreateInput("5000", 139, 164, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtDERedDead = GUICtrlCreateInput("100", 139, 189, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetTip(-1, "Enter number of individual units to train")
$txtTroRedDead = GUICtrlCreateInput("2", 139, 214, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkredDead = GUICtrlCreateCheckbox("Enable", 19, 92, 75, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Enable Search Reduction for Dead Base")
$txtRedSearchDead = GUICtrlCreateInput("20", 139, 239, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblGoldElixRedDead = GUICtrlCreateLabel("Gold and Elixir Reduce:", 19, 117, 115, 17)
$txtGoldElixRedDead = GUICtrlCreateInput("5000", 139, 114, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlCreateGroup("", -99, -99, 1, 1)
$GroupRedAny = GUICtrlCreateGroup("Any Base Search Reduction", 219, 67, 200, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblGoldRedAny = GUICtrlCreateLabel("Gold Reduce:", 229, 142, 70, 17)
$lblElixRedAny = GUICtrlCreateLabel("Elixir Reduce:", 229, 167, 70, 17)
$lblDERedAny = GUICtrlCreateLabel("DE Reduce:", 229, 192, 85, 17)
$lblTroRedAny = GUICtrlCreateLabel("Trophy Reduce:", 229, 217, 85, 17)
$lblRedSearchAny = GUICtrlCreateLabel("After Search:", 229, 242, 80, 17)
$txtGoldRedAny = GUICtrlCreateInput("5000", 349, 139, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtElixRedAny = GUICtrlCreateInput("5000", 349, 164, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtDERedAny = GUICtrlCreateInput("100", 349, 189, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetTip(-1, "Enter number of individual units to train")
$txtTroRedAny = GUICtrlCreateInput("2", 349, 214, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkredAny = GUICtrlCreateCheckbox("Enable", 229, 92, 75, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Enable Search Reduction for Any Base")
$txtRedSearchAny = GUICtrlCreateInput("20", 349, 239, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblGoldElixRedAny = GUICtrlCreateLabel("Gold and Elixir Reduce:", 229, 117, 115, 17)
$txtGoldElixRedAny = GUICtrlCreateInput("5000", 349, 114, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupAvoidDef = GUICtrlCreateGroup("Avoid Defend", 429, 69, 200, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkInfTow = GUICtrlCreateCheckbox("Inferno Tower", 439, 94, 85, 15)
$btnCheckDefense = GUICtrlCreateButton("Button 1", 439, 117, 75, 25)
GUICtrlSetState(-1, $GUI_HIDE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageAttackSettings = GUICtrlCreateTabItem("Attack")
$groupDeadDeploySettings = GUICtrlCreateGroup("Dead Base Deploy Settings", 7, 62, 610, 90)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$cmbDeadDeploy = GUICtrlCreateCombo("", 22, 84, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Attack on a single side, penetrates through base|Attack on two sides, penetrates through base|Attack on three sides, gets outer and some inside of base|Attack on all sides equally, gets most of outer base")
$cmbDeadAlgorithm = GUICtrlCreateCombo("", 22, 119, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks|Use All Troops")
$chkDeadUseKing = GUICtrlCreateCheckbox("Attack with King", 337, 84, 102, 17)
$chkDeadUseQueen = GUICtrlCreateCheckbox("Attack with Queen", 337, 119, 110, 17)
$chkDeadUseClanCastle = GUICtrlCreateCheckbox("Attack with Clan Castle troops", 444, 84, 165, 17)
$cmbDeadAttackTH = GUICtrlCreateCombo("", 452, 116, 145, 25)
GUICtrlSetData(-1, "Dont attack TH|Limited TH attack|Full TH attack")
GUICtrlSetTip(-1, "Troops can either not focus on townhall, send a single wave of archers and barbarians at the townhall, or focus all troops on townhall")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupAnyDeploySettings = GUICtrlCreateGroup("Other Base Deploy Settings", 7, 157, 610, 90)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$cmbDeploy = GUICtrlCreateCombo("", 22, 179, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Attack on a single side, penetrates through base|Attack on two sides, penetrates through base|Attack on three sides, gets outer and some inside of base|Attack on all sides equally, gets most of outer base")
$cmbAlgorithm = GUICtrlCreateCombo("", 22, 214, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks|Use All Troops")
$chkUseKing = GUICtrlCreateCheckbox("Attack with King", 337, 179, 102, 17)
$chkUseQueen = GUICtrlCreateCheckbox("Attack with Queen", 337, 214, 110, 17)
$chkUseClanCastle = GUICtrlCreateCheckbox("Attack with Clan Castle troops", 444, 179, 157, 17)
$cmbAttackTH = GUICtrlCreateCombo("", 452, 211, 145, 25)
GUICtrlSetData(-1, "Dont attack TH|Limited TH attack|Full TH attack")
GUICtrlSetTip(-1, "Troops can either not focus on townhall, send a single wave of archers and barbarians at the townhall, or focus all troops on townhall")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupDeploySpeed = GUICtrlCreateGroup("Deploy Speed", 302, 259, 320, 110)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblUnitDelay = GUICtrlCreateLabel("Unit Delay:", 312, 289, 65, 17)
$cmbUnitDelay = GUICtrlCreateCombo("", 382, 284, 50, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "1|2|3|4|5|6|7|8|9|10")
$lblWaveDelay = GUICtrlCreateLabel("Wave Delay:", 312, 319, 65, 17)
$cmbWaveDelay = GUICtrlCreateCombo("", 382, 314, 50, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "1|2|3|4|5|6|7|8|9|10")
$chkRandomSpeedAtk = GUICtrlCreateCheckbox("Random Speeds!!", 317, 342, 100, 17)
$lblAttackDelay1 = GUICtrlCreateLabel("Delays for troop deployment", 436, 273, 180, 18, $SS_CENTER)
GUICtrlSetFont(-1, 9, 400, 4, "Arial")
$lblAttackDelay2 = GUICtrlCreateLabel("- [1] Fast = Bot Like!", 460, 290, 99, 18)
$lblAttackDelay3 = GUICtrlCreateLabel("- [10] Slow = Human Like!", 460, 306, 126, 18)
$lblAttackDelay4 = GUICtrlCreateLabel("Random will make bot more variant", 436, 330, 171, 18, $SS_CENTER)
$lblAttackDelay5 = GUICtrlCreateLabel("and closer to human!", 436, 347, 104, 18, $SS_CENTER)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageDonateSettings = GUICtrlCreateTabItem("Donate")
$groupBarbarians = GUICtrlCreateGroup("Option 1", 4, 54, 166, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDonateAllBarbarians = GUICtrlCreateCheckbox("Donate to All Request", 19, 72, 120, 14)
GUICtrlSetTip(-1, "Donate to all request regardless Donation Text")
$txtDonateBarbarians = GUICtrlCreateEdit("", 14, 104, 146, 111)
GUICtrlSetData(-1, "")
GUICtrlSetTip(-1, "Keywords for option 1")
$cmbDonateBarbarians1 = GUICtrlCreateCombo("", 14, 219, 89, 25)
GUICtrlSetData(-1, "Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$cmbDonateBarbarians2 = GUICtrlCreateCombo("", 14, 243, 89, 25)
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$cmbDonateBarbarians3 = GUICtrlCreateCombo("", 14, 267, 89, 25)
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$NoOfBarbarians1 = GUICtrlCreateInput("5", 126, 219, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$NoOfBarbarians2 = GUICtrlCreateInput("1", 126, 243, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$NoOfBarbarians3 = GUICtrlCreateInput("1", 126, 267, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkDonateBarbarians = GUICtrlCreateCheckbox("Smart Donate", 19, 89, 82, 14)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Donate Troop base on Setting and Donation Text")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupArchers = GUICtrlCreateGroup("Option 2", 172, 54, 166, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDonateAllArchers = GUICtrlCreateCheckbox("Donate to All Request", 187, 72, 120, 14)
GUICtrlSetTip(-1, "Donate to all request regardless Donation Text")
$txtDonateArchers = GUICtrlCreateEdit("", 182, 104, 146, 111)
GUICtrlSetData(-1, "")
GUICtrlSetTip(-1, "Keywords for option 2")
$cmbDonateArchers1 = GUICtrlCreateCombo("", 182, 219, 89, 25)
GUICtrlSetData(-1, "Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$cmbDonateArchers2 = GUICtrlCreateCombo("", 183, 243, 89, 25)
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$cmbDonateArchers3 = GUICtrlCreateCombo("", 183, 267, 89, 25)
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$NoOfArchers1 = GUICtrlCreateInput("5", 294, 219, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$NoOfArchers2 = GUICtrlCreateInput("1", 294, 243, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$NoOfArchers3 = GUICtrlCreateInput("1", 294, 267, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkDonateArchers = GUICtrlCreateCheckbox("Smart Donate", 187, 89, 82, 14)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Donate Troop base on Setting and Donation Text")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupGiants = GUICtrlCreateGroup("Option 3", 340, 54, 166, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDonateAllGiants = GUICtrlCreateCheckbox("Donate to All Request", 355, 72, 120, 14)
GUICtrlSetTip(-1, "Donate to all request regardless Donation Text")
$txtDonateGiants = GUICtrlCreateEdit("", 350, 104, 146, 111)
GUICtrlSetData(-1, "")
GUICtrlSetTip(-1, "Keywords for option 3")
$cmbDonateGiants1 = GUICtrlCreateCombo("", 350, 219, 89, 25)
GUICtrlSetData(-1, "Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$cmbDonateGiants2 = GUICtrlCreateCombo("", 350, 243, 89, 25)
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$cmbDonateGiants3 = GUICtrlCreateCombo("", 350, 267, 89, 25)
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava")
$NoOfGiants1 = GUICtrlCreateInput("5", 462, 219, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$NoOfGiants2 = GUICtrlCreateInput("1", 462, 243, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$NoOfGiants3 = GUICtrlCreateInput("1", 462, 267, 33, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkDonateGiants = GUICtrlCreateCheckbox("Smart Donate", 355, 89, 82, 14)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Donate Troop base on Setting and Donation Text")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$chkRequest = GUICtrlCreateCheckbox("Request for :", 294, 310, 82, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$txtRequest = GUICtrlCreateInput("Any", 379, 307, 250, 23)
GUICtrlSetFont(-1, 9, 400, 0, "Arial")
GUICtrlSetTip(-1, "Request for input.")
$groupNotDonate = GUICtrlCreateGroup("Donation Blacklist", 514, 54, 114, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$txtNotDonate = GUICtrlCreateEdit("", 524, 95, 94, 190)
GUICtrlSetData(-1, "")
GUICtrlSetTip(-1, "Blacklist Keywords")
$chkBlacklist = GUICtrlCreateCheckbox("Enable", 529, 72, 50, 14)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageTroopSettings = GUICtrlCreateTabItem("Troops")
$groupTroops = GUICtrlCreateGroup("Troops", 12, 57, 200, 240)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBarbarians = GUICtrlCreateLabel("Barb", 22, 82, 45, 17)
$lblArchers = GUICtrlCreateLabel("Archer", 22, 107, 45, 17)
$lblGoblins = GUICtrlCreateLabel("Goblin", 22, 132, 45, 17)
$txtBarbarians = GUICtrlCreateInput("30", 112, 79, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtArchers = GUICtrlCreateInput("60", 112, 104, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtGoblins = GUICtrlCreateInput("10", 112, 129, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblPercentBarbarians = GUICtrlCreateLabel("%", 172, 82, 12, 17)
$lblPercentArchers = GUICtrlCreateLabel("%", 172, 107, 12, 17)
$lblPercentGoblins = GUICtrlCreateLabel("%", 172, 131, 12, 17)
$lblGiants = GUICtrlCreateLabel("Giants :", 22, 157, 85, 17)
$lblWallBreakers = GUICtrlCreateLabel("Wall Breakers :", 22, 182, 85, 17)
$txtNumGiants = GUICtrlCreateInput("4", 112, 154, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetTip(-1, "Enter number of individual units to train")
$txtNumWallbreakers = GUICtrlCreateInput("4", 112, 179, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetTip(-1, "Enter number of individual units to train")
$lblCapacity = GUICtrlCreateLabel("Camp Capacity :", 22, 207, 85, 17)
$txtCapacity = GUICtrlCreateInput("0", 112, 204, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblRaidcap = GUICtrlCreateLabel("Raid Capacity :", 22, 232, 85, 17)
$cmbRaidcap = GUICtrlCreateCombo("", 112, 229, 56, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "10|20|30|40|50|60|70|80|90|100")
$lblPercentCapacity = GUICtrlCreateLabel("%", 172, 232, 12, 17)
$cmbTroopComp = GUICtrlCreateCombo("", 22, 261, 175, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|B.Arch|B.A.G.G.|B.A.Giant|B.A.Goblin|B.A.G.G.Wall|Use Barracks|Custom Troops|Custom Troops 2")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupCustomTroops2 = GUICtrlCreateGroup("Custom Troops 2", 232, 57, 395, 121)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBarrackJOE1 = GUICtrlCreateLabel("Barrack 1 :", 242, 76, 53, 17)
$lblBarrackJOE2 = GUICtrlCreateLabel("Barrack 2 :", 242, 101, 53, 17)
$lblBarrackJOE3 = GUICtrlCreateLabel("Barrack 3 :", 242, 126, 53, 17)
$lblBarrackJOE4 = GUICtrlCreateLabel("Barrack 4 :", 242, 151, 53, 17)
$lblBarrackBK1 = GUICtrlCreateLabel("the rest", 447, 76, 40, 17)
$lblBarrackBK2 = GUICtrlCreateLabel("the rest", 447, 101, 40, 17)
$lblBarrackBK3 = GUICtrlCreateLabel("the rest", 447, 126, 40, 17)
$lblBarrackBK4 = GUICtrlCreateLabel("the rest", 447, 151, 40, 17)
$txtFirstTroop1 = GUICtrlCreateInput("2", 302, 73, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtFirstTroop2 = GUICtrlCreateInput("2", 302, 98, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtFirstTroop3 = GUICtrlCreateInput("2", 302, 123, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtFirstTroop4 = GUICtrlCreateInput("2", 302, 148, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$cmbFirstTroop1 = GUICtrlCreateCombo("", 342, 73, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing")
$cmbFirstTroop2 = GUICtrlCreateCombo("", 342, 98, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing")
$cmbFirstTroop3 = GUICtrlCreateCombo("", 342, 123, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing")
$cmbFirstTroop4 = GUICtrlCreateCombo("", 342, 148, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing")
$cmbSecondTroop1 = GUICtrlCreateCombo("", 497, 73, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing")
$cmbSecondTroop2 = GUICtrlCreateCombo("", 497, 98, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing")
$cmbSecondTroop3 = GUICtrlCreateCombo("", 497, 123, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing")
$cmbSecondTroop4 = GUICtrlCreateCombo("", 497, 148, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupBarracks = GUICtrlCreateGroup("Barracks", 232, 177, 185, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBarrack1 = GUICtrlCreateLabel("Barrack 1:", 242, 197, 53, 17)
$lblBarrack2 = GUICtrlCreateLabel("Barrack 2:", 242, 222, 53, 17)
$lblBarrack3 = GUICtrlCreateLabel("Barrack 3:", 243, 247, 53, 17)
$lblBarrack4 = GUICtrlCreateLabel("Barrack 4:", 243, 272, 53, 17)
$cmbBarrack1 = GUICtrlCreateCombo("", 297, 193, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard||||Nothing")
$cmbBarrack2 = GUICtrlCreateCombo("", 297, 218, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard||||Nothing")
$cmbBarrack3 = GUICtrlCreateCombo("", 298, 243, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard||||Nothing")
$cmbBarrack4 = GUICtrlCreateCombo("", 298, 268, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard||||Nothing")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupDarkTroops = GUICtrlCreateGroup("Dark Troops", 422, 177, 204, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDarkTroop = GUICtrlCreateCheckbox("Enabled", 434, 199, 80, 15)
$lblDarkBarrack1 = GUICtrlCreateLabel("Dark Barrack 1:", 432, 225, 80, 17)
$lblDarkBarrack2 = GUICtrlCreateLabel("Dark Barrack 2:", 432, 256, 80, 17)
$cmbDarkBarrack1 = GUICtrlCreateCombo("", 547, 221, 70, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Minions|Hogs|Valkyries|Nothing")
$cmbDarkBarrack2 = GUICtrlCreateCombo("", 547, 252, 70, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Minions|Hogs|Valkyries|Nothing")
$txtDarkBarrack1 = GUICtrlCreateInput("5", 512, 221, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtDarkBarrack2 = GUICtrlCreateInput("5", 512, 252, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageUpgradeSettings = GUICtrlCreateTabItem("Upgrades")
$groupWalls = GUICtrlCreateGroup("Walls", 12, 62, 470, 125)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkWalls = GUICtrlCreateCheckbox("Auto Wall Upgrade", 22, 84, 110, 17)
$UseGold = GUICtrlCreateRadio("Use Only Gold", 32, 109, 115, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
$lblWallMinGold = GUICtrlCreateLabel("Minimum Gold:", 282, 139, 76, 17)
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform the upgrade")
$txtWallMinGold = GUICtrlCreateInput("1300000", 402, 134, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform the upgrade")
$UseElixir = GUICtrlCreateRadio("Use Only Elixir", 32, 134, 115, 17)
$lblWallMinElixir = GUICtrlCreateLabel("Minimum Elixir:", 282, 164, 72, 17)
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform the upgrade")
$txtWallMinElixir = GUICtrlCreateInput("1300000", 402, 159, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform the upgrade")
$UseGoldElix = GUICtrlCreateRadio("Use Gold and then Elixir", 32, 159, 150, 17)
$lblWalls = GUICtrlCreateLabel("Current Wall Level:", 282, 86, 100, 17)
$cmbWalls = GUICtrlCreateCombo("", 402, 82, 40, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "4|5|6|7|8|9|10")
$lblTolerance = GUICtrlCreateLabel("Tolerance Level:", 282, 114, 80, 17)
$cmbTolerance = GUICtrlCreateCombo("", 402, 109, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Default|Lower|Higher")
$btnFindWall = GUICtrlCreateButton("Find Wall", 137, 82, 63, 21)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupUpgrade = GUICtrlCreateGroup("Buildings / Walls Upgrade", 12, 187, 470, 105)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkUpgrade1 = GUICtrlCreateCheckbox("Upgrade 1 :", 22, 204, 80, 17)
$lblUP1PosX = GUICtrlCreateLabel("Pos X :", 104, 206, 35, 17)
$txtUpgradeX1 = GUICtrlCreateInput("", 144, 201, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
$lblUP1PosY = GUICtrlCreateLabel("Pos Y :", 187, 206, 35, 17)
$txtUpgradeY1 = GUICtrlCreateInput("", 227, 201, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
$btnLocateUp1 = GUICtrlCreateButton("Locate Building 1", 277, 201, 100, 21)
$chkUpgrade2 = GUICtrlCreateCheckbox("Upgrade 2 :", 22, 234, 80, 17)
$lblUP2PosX = GUICtrlCreateLabel("Pos X :", 104, 236, 35, 17)
$txtUpgradeX2 = GUICtrlCreateInput("", 144, 231, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
$lblUP2PosY = GUICtrlCreateLabel("Pos Y :", 187, 236, 35, 17)
$txtUpgradeY2 = GUICtrlCreateInput("", 227, 231, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
$btnLocateUp2 = GUICtrlCreateButton("Locate Building 2", 277, 231, 100, 21)
$chkUpgrade3 = GUICtrlCreateCheckbox("Upgrade 3 :", 22, 264, 80, 17)
$lblUP3PosX = GUICtrlCreateLabel("Pos X :", 104, 266, 35, 17)
$txtUpgradeX3 = GUICtrlCreateInput("", 144, 261, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
$lblUP3PosY = GUICtrlCreateLabel("Pos Y :", 187, 266, 35, 17)
$txtUpgradeY3 = GUICtrlCreateInput("", 227, 261, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
$btnLocateUp3 = GUICtrlCreateButton("Locate Building 3", 277, 261, 100, 21)
$lblBldgMinGold = GUICtrlCreateLabel("Minimum Gold:", 392, 201, 76, 17)
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform building upgrade")
$lblBldgMinElixir = GUICtrlCreateLabel("Minimum Elixir:", 392, 245, 72, 17)
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform building upgrade")
$txtBldgMinGold = GUICtrlCreateInput("1300000", 397, 219, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform Building upgrade")
$txtBldgMinElixir = GUICtrlCreateInput("1300000", 397, 263, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform Building upgrade")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupBoosts = GUICtrlCreateGroup("Boosts", 489, 62, 130, 310)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBoostBarracks = GUICtrlCreateLabel("Boosts left :", 499, 86, 60, 17)
$cmbBoostBarracks = GUICtrlCreateCombo("", 569, 82, 40, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "0|1|2|3|4|5|6|7|8|9|10")
$chkBoostKing = GUICtrlCreateCheckbox("King Altar", 499, 112, 65, 17)
$chkBoostQueen = GUICtrlCreateCheckbox("Queen Altar", 499, 137, 75, 17)
$chkBoostRax1 = GUICtrlCreateCheckbox("Barrack 1", 499, 162, 65, 17)
$chkBoostRax2 = GUICtrlCreateCheckbox("Barrack 2", 499, 187, 65, 17)
$chkBoostRax3 = GUICtrlCreateCheckbox("Barrack 3", 499, 212, 65, 17)
$chkBoostRax4 = GUICtrlCreateCheckbox("Barrack 4", 499, 237, 65, 17)
$chkBoostDark1 = GUICtrlCreateCheckbox("Dark Barrack 1", 499, 262, 90, 17)
$chkBoostDark2 = GUICtrlCreateCheckbox("Dark Barrack 2", 499, 287, 90, 17)
$chkBoostSpell = GUICtrlCreateCheckbox("Spell Factory", 499, 312, 80, 17)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageMiscSettings = GUICtrlCreateTabItem("Misc")
$groupMiscs = GUICtrlCreateGroup("Misc", 12, 62, 600, 235)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblReconnect = GUICtrlCreateLabel("Reconnect Interval:", 22, 82, 98, 17)
GUICtrlSetTip(-1, "Set reconnect interval when other devices connected - COC English version Only")
$txtReconnect = GUICtrlCreateInput("2", 122, 78, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblReconnectmin = GUICtrlCreateLabel("minutes", 157, 82, 42, 17)
$chkTrap = GUICtrlCreateCheckbox("Auto Rearm Traps", 167, 244, 110, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Auto rearm for Traps, Crossbows  Inferno Towers")
$lblSearchsp = GUICtrlCreateLabel("Seach Base Speed:", 22, 109, 98, 17)
GUICtrlSetTip(-1, "Set search base speed to higher number if having frequent server sync issue")
$lblSearchspd = GUICtrlCreateLabel("Tips: 0 = Fast, 9 = Slow", 157, 109, 120, 17)
$UseSkillTimed = GUICtrlCreateRadio("King Skill Delay:", 22, 137, 95, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Set delay timing for King skill")
$txtKingSkill = GUICtrlCreateInput("10", 122, 133, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblKingsSkill = GUICtrlCreateLabel("seconds   /", 157, 137, 60, 17)
$lblQueenSkill = GUICtrlCreateLabel("Queen Skill Delay:", 222, 137, 88, 17)
GUICtrlSetTip(-1, "Set delay timing for Queen skill")
$txtQueenSkill = GUICtrlCreateInput("10", 312, 133, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblQueensSkill = GUICtrlCreateLabel("seconds", 347, 137, 45, 17)
$lblReturnh = GUICtrlCreateLabel("Return Home Delay:", 22, 190, 98, 17)
GUICtrlSetTip(-1, "Set delay timing for return home during raid")
$txtReturnh = GUICtrlCreateInput("10", 122, 186, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblReturndelay = GUICtrlCreateLabel("seconds after No Income", 157, 190, 125, 17)
$chkSpellDarkStorage = GUICtrlCreateCheckbox("Cast Lightning when left:", 22, 216, 137, 17)
GUICtrlSetTip(-1, "Set Min Dark Elixir to Lightning Dark Storage")
$txtSpellDarkStorage = GUICtrlCreateInput("500", 162, 212, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblSpellDarkStorage = GUICtrlCreateLabel("Dark Elixir", 197, 217, 50, 17)
$chkTakeTownSS = GUICtrlCreateCheckbox("Take All Towns Snapshot", 462, 272, 141, 17)
$chkTakeLootSS = GUICtrlCreateCheckbox("Take Loots Snapshot", 312, 272, 118, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
$chkAlertSearch = GUICtrlCreateCheckbox("Base Found Alert", 167, 272, 100, 17)
$UseSkillAuto = GUICtrlCreateRadio("Auto Activate Heroes Skill on Low Health", 22, 163, 215, 17)
GUICtrlSetTip(-1, "Skill will activate when hero's health is low")
$chkRaxRestart = GUICtrlCreateCheckbox("Restart Bluestack if Fail to Locate All 4 Barracks", 312, 81, 250, 17)
GUICtrlSetTip(-1, "Restart bluestack if fail to detect all 4 barracks")
$chkMultiLight = GUICtrlCreateCheckbox("Smart Lightning Spell", 312, 216, 120, 17)
GUICtrlSetTip(-1, "Cast Lightning as long as Dark Elixir more than Min requirement")
$chkkeeplogs = GUICtrlCreateCheckbox("Keep Logs:", 22, 272, 70, 17)
GUICtrlSetTip(-1, "Set number of logs you want to keep")
$txtkeeplogs = GUICtrlCreateInput("20", 97, 268, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$chkWideEdge = GUICtrlCreateCheckbox("Search Deeper Townhall", 312, 244, 136, 17)
GUICtrlSetTip(-1, "Increase the range for Townhall to be considering as Outside")
$chkRedLine = GUICtrlCreateCheckbox("Attack Near Red Line", 462, 244, 120, 17)
GUICtrlSetTip(-1, "Look for red line and deploy troops near them")
$txtSearchsp = GUICtrlCreateInput("3", 122, 105, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$txtwhitecloud = GUICtrlCreateInput("30", 442, 105, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$Label22 = GUICtrlCreateLabel("seconds", 477, 109, 45, 17)
$lblwhitecloud = GUICtrlCreateLabel("White Cloud Waiting Time:", 312, 109, 128, 17)
GUICtrlSetTip(-1, "Set waiting time for next base when searching")
$chkCollect = GUICtrlCreateCheckbox("Auto Collect Resource", 22, 244, 125, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Auto Collect All Available Resource")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageStatsSetting = GUICtrlCreateTabItem("Stats")
$groupResourceAtStart = GUICtrlCreateGroup("Resources at Start", 12, 62, 185, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldonstart = GUICtrlCreateLabel("Gold at Start :", 42, 90, 75, 17)
$lblresultgoldtstart = GUICtrlCreateLabel("0", 122, 90, 60, 17, $SS_RIGHT)
$imgGoldStart = GUICtrlCreatePic("", 22, 90, 15, 15)
$lblelixironstart = GUICtrlCreateLabel("Elixir at Start :", 42, 110, 75, 17)
$lblresultelixirstart = GUICtrlCreateLabel("0", 122, 110, 60, 17, $SS_RIGHT)
$imgElixirStart = GUICtrlCreatePic("", 22, 110, 15, 15)
$lbldeonstart = GUICtrlCreateLabel("DE at Start :", 42, 130, 75, 17)
$lblresultdestart = GUICtrlCreateLabel("0", 122, 130, 60, 17, $SS_RIGHT)
$imgDarkStart = GUICtrlCreatePic("", 22, 130, 15, 15)
$lbltrophyonstart = GUICtrlCreateLabel("Trophies at Start :", 42, 150, 90, 17)
$lblresulttrophystart = GUICtrlCreateLabel("0", 137, 150, 45, 17, $SS_RIGHT)
$imgTrophyStart = GUICtrlCreatePic("", 22, 150, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupOtherStats = GUICtrlCreateGroup("Other Stats", 429, 62, 185, 230)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblvillagesattacked = GUICtrlCreateLabel("Attacked :", 439, 86, 80, 17)
$lblresultvillagesattacked = GUICtrlCreateLabel("0", 539, 86, 60, 17, $SS_RIGHT)
$lblvillagesskipped = GUICtrlCreateLabel("Skipped :", 439, 106, 80, 17)
$lblresultvillagesskipped = GUICtrlCreateLabel("0", 539, 106, 60, 17, $SS_RIGHT)
$lblwallupgrade = GUICtrlCreateLabel("Wall Upgrades :", 439, 126, 80, 17)
$lblwallupgradecount = GUICtrlCreateLabel("0", 539, 126, 60, 17, $SS_RIGHT)
$lblsearchcost = GUICtrlCreateLabel("Search Cost :", 439, 146, 80, 17)
$lblresultsearchcost = GUICtrlCreateLabel("0", 539, 146, 60, 17, $SS_RIGHT)
$lblbuilder = GUICtrlCreateLabel("Builder :", 439, 166, 80, 17)
$lblresultbuilder = GUICtrlCreateLabel("0", 539, 166, 60, 17, $SS_RIGHT)
$lblruntime = GUICtrlCreateLabel("Bot Run Time :", 439, 266, 80, 17)
$lblresultruntime = GUICtrlCreateLabel("00:00:00", 539, 266, 60, 17, $SS_RIGHT)
$lbloos = GUICtrlCreateLabel("Disconnect :", 439, 186, 80, 17)
$lblresultoos = GUICtrlCreateLabel("0", 539, 186, 60, 17, $SS_RIGHT)
$lblgoldperhour = GUICtrlCreateLabel("Gold / Hour :", 439, 206, 80, 18)
$lblelixirperhour = GUICtrlCreateLabel("Elixir / Hour :", 439, 226, 80, 18)
$lblresultgph = GUICtrlCreateLabel("0", 539, 206, 60, 18, $SS_RIGHT)
$lblresulteph = GUICtrlCreateLabel("0", 539, 226, 60, 18, $SS_RIGHT)
$lbldeperhour = GUICtrlCreateLabel("DE / Hour :", 439, 246, 80, 18)
$lblresultdeph = GUICtrlCreateLabel("0", 539, 246, 60, 18, $SS_RIGHT)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupLastRaid = GUICtrlCreateGroup("Last Raid Loot", 12, 182, 185, 110)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldlast = GUICtrlCreateLabel("Gold Loot:", 42, 207, 60, 17)
$lblresultgoldlast = GUICtrlCreateLabel("0", 120, 207, 60, 17, $SS_RIGHT)
$imgGoldLast = GUICtrlCreatePic("", 22, 207, 15, 15)
$lblelixirlast = GUICtrlCreateLabel("Elixir Loot:", 42, 227, 60, 17)
$lblresultelixirlast = GUICtrlCreateLabel("0", 120, 227, 60, 17, $SS_RIGHT)
$imgElixirLast = GUICtrlCreatePic("", 22, 227, 15, 15)
$lbldelast = GUICtrlCreateLabel("DE Loot:", 42, 247, 60, 17)
$lblresultdelast = GUICtrlCreateLabel("0", 120, 247, 60, 17, $SS_RIGHT)
$imgDarkLast = GUICtrlCreatePic("", 22, 247, 15, 15)
$lbltrophylast = GUICtrlCreateLabel("Trophies Won :", 42, 267, 75, 17)
$lblresulttrophylast = GUICtrlCreateLabel("0", 120, 267, 60, 17, $SS_RIGHT)
$imgTrophyLast = GUICtrlCreatePic("", 22, 267, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupCurrentResources = GUICtrlCreateGroup("Current Resources", 219, 62, 185, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldnow = GUICtrlCreateLabel("Gold Now :", 249, 90, 75, 17)
$lblresultgoldnow = GUICtrlCreateLabel("0", 329, 90, 60, 17, $SS_RIGHT)
$imgGoldCurrent = GUICtrlCreatePic("", 229, 90, 15, 15)
$lblelixirnow = GUICtrlCreateLabel("Elixir Now :", 249, 110, 75, 17)
$lblresultelixirnow = GUICtrlCreateLabel("0", 329, 110, 60, 17, $SS_RIGHT)
$imgElixirCurrent = GUICtrlCreatePic("", 229, 110, 15, 15)
$lbldenow = GUICtrlCreateLabel("DE Now :", 249, 130, 75, 17)
$lblresultdenow = GUICtrlCreateLabel("0", 329, 130, 60, 17, $SS_RIGHT)
$imgDarkCurrent = GUICtrlCreatePic("", 229, 130, 15, 15)
$lbltrophynow = GUICtrlCreateLabel("Trophies Now :", 249, 150, 75, 17)
$lblresulttrophynow = GUICtrlCreateLabel("0", 329, 150, 60, 17, $SS_RIGHT)
$imgTrophyCurrent = GUICtrlCreatePic("", 229, 150, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupTotalRaid = GUICtrlCreateGroup("Total Loot", 219, 182, 185, 110)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldgain = GUICtrlCreateLabel("Gold Gain :", 249, 205, 75, 17)
$lblresultgoldgain = GUICtrlCreateLabel("0", 329, 205, 60, 17, $SS_RIGHT)
$imgGoldTotal = GUICtrlCreatePic("", 229, 205, 15, 15)
$lblelixirgain = GUICtrlCreateLabel("Elixir Gain :", 249, 225, 75, 17)
$lblresultelixirgain = GUICtrlCreateLabel("0", 329, 225, 60, 17, $SS_RIGHT)
$imgElixirTotal = GUICtrlCreatePic("", 229, 225, 15, 15)
$lbldegain = GUICtrlCreateLabel("DE Gain :", 249, 245, 75, 17)
$lblresultdegain = GUICtrlCreateLabel("0", 329, 245, 60, 17, $SS_RIGHT)
$imgDarkTotal = GUICtrlCreatePic("", 229, 245, 15, 15)
$lbltrophiesdropped = GUICtrlCreateLabel("Trophies Won :", 249, 265, 75, 17)
$lblresulttrophiesdropped = GUICtrlCreateLabel("0", 329, 265, 60, 17, $SS_RIGHT)
$imgTrophyTotal = GUICtrlCreatePic("", 229, 265, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageNotificationSetting = GUICtrlCreateTabItem("Notification")
$groupPushBullet = GUICtrlCreateGroup("PushBullet", 4, 62, 375, 231)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblPushBulletToken = GUICtrlCreateLabel("Account Token:", 14, 112, 80, 17, $SS_CENTER)
$txtPushBulletTokenValue = GUICtrlCreateInput("", 104, 112, 260, 22)
$chkPushBulletEnabled = GUICtrlCreateCheckbox("Enable", 14, 87, 60, 17)
GUICtrlSetTip(-1, "Enable pushbullet notification")
$chkPushBulletDebug = GUICtrlCreateCheckbox("Debug", 84, 87, 60, 17)
GUICtrlSetTip(-1, "This will add verbosity on log while sending files via pushbullet")
$chkPushBulletRemote = GUICtrlCreateCheckbox("Remote", 154, 87, 60, 17)
GUICtrlSetTip(-1, "Enables pushbullet remote function")
$chkPushBulletDelete = GUICtrlCreateCheckbox("Delete All Msg on Start", 224, 87, 128, 17)
GUICtrlSetTip(-1, "Will delete all messages when bot starts")
$groupPushMessages = GUICtrlCreateGroup("Push Messages", 14, 137, 260, 67)
$chkPushVillageReport = GUICtrlCreateCheckbox("Village Report", 24, 159, 90, 17)
$chkPushMatchFound = GUICtrlCreateCheckbox("Match Found", 24, 176, 90, 17)
$chkPushLastRaid = GUICtrlCreateCheckbox("Last Raid", 114, 159, 70, 17)
$chkPushTotalRaid = GUICtrlCreateCheckbox("Total Raid", 114, 176, 70, 17)
$chkPushFreeBuilder = GUICtrlCreateCheckbox("Free Builder", 187, 159, 75, 17)
$chkPushError = GUICtrlCreateCheckbox("Errors", 188, 176, 70, 17)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupPushLastRaid = GUICtrlCreateGroup("Last Raid", 284, 137, 80, 67)
$UseJPG = GUICtrlCreateRadio("as JPG", 294, 159, 60, 17)
GUICtrlSetTip(-1, "Attach the loot jpg file in push message")
$UseText = GUICtrlCreateRadio("as TXT", 294, 176, 60, 17)
GUICtrlSetTip(-1, "Push only text message")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupRemoteConfig = GUICtrlCreateGroup("Misc.", 204, 206, 161, 75)
$lblPushBulletInterval = GUICtrlCreateLabel("Check Interval:", 214, 231, 82, 17)
$txtPushBulletInterval = GUICtrlCreateInput("10", 299, 226, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblPushBulletIntervalMin = GUICtrlCreateLabel("mins", 334, 231, 29, 17)
$txtPushBulletMessages = GUICtrlCreateInput("100", 299, 251, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
$lblPushBulletMessages = GUICtrlCreateLabel("Keep Messages:", 214, 256, 82, 17)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$Group2 = GUICtrlCreateGroup("PushBullet Settings", 12, 206, 185, 75)
$Label31 = GUICtrlCreateLabel("Device:", 20, 240, 40, 18)
$cmbDevice = GUICtrlCreateCombo("All", 66, 237, 121, 25)
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$Group1 = GUICtrlCreateGroup("Help", 396, 61, 233, 289)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$Label2 = GUICtrlCreateLabel("You can remotely control your bot using", 406, 82, 197, 18, $SS_CENTERIMAGE)
$Label3 = GUICtrlCreateLabel("the following command format", 406, 96, 149, 18, $SS_CENTERIMAGE)
$Label4 = GUICtrlCreateLabel("Bot <command> where <command> is:", 406, 119, 191, 18, $SS_CENTERIMAGE)
$Label5 = GUICtrlCreateLabel("Pause", 406, 143, 34, 18, $SS_CENTERIMAGE)
$Label6 = GUICtrlCreateLabel("Resume", 406, 158, 43, 18, $SS_CENTERIMAGE)
$Label7 = GUICtrlCreateLabel("Stats", 406, 173, 29, 18, $SS_CENTERIMAGE)
$Label8 = GUICtrlCreateLabel("Logs", 406, 188, 28, 18, $SS_CENTERIMAGE)
$Label9 = GUICtrlCreateLabel("Boost1", 406, 203, 38, 18, $SS_CENTERIMAGE)
$Label10 = GUICtrlCreateLabel("Boost2", 406, 218, 38, 18, $SS_CENTERIMAGE)
$Label11 = GUICtrlCreateLabel("Boost3", 406, 234, 38, 18, $SS_CENTERIMAGE)
$Label12 = GUICtrlCreateLabel("BoostAll", 406, 248, 44, 18, $SS_CENTERIMAGE)
$Label13 = GUICtrlCreateLabel("Help", 406, 262, 25, 18, $SS_CENTERIMAGE)
$Label1 = GUICtrlCreateLabel("- pause the bot", 466, 143, 77, 18, $SS_CENTERIMAGE)
$Label14 = GUICtrlCreateLabel("- send this help message", 466, 262, 125, 18, $SS_CENTERIMAGE)
$Label15 = GUICtrlCreateLabel("- Boost all barracks", 466, 248, 98, 18, $SS_CENTERIMAGE)
$Label16 = GUICtrlCreateLabel("- Boost 3 barracks", 466, 234, 94, 18, $SS_CENTERIMAGE)
$Label17 = GUICtrlCreateLabel("- Boost 2 barracks", 466, 218, 94, 18, $SS_CENTERIMAGE)
$Label18 = GUICtrlCreateLabel("- Boost 1 barrack", 466, 203, 88, 18, $SS_CENTERIMAGE)
$Label19 = GUICtrlCreateLabel("- send the current log file", 466, 188, 125, 18, $SS_CENTERIMAGE)
$Label20 = GUICtrlCreateLabel("- send bot current statistics", 466, 173, 137, 18, $SS_CENTERIMAGE)
$Label21 = GUICtrlCreateLabel("- resume the bot", 466, 158, 83, 18, $SS_CENTERIMAGE)
$Label23 = GUICtrlCreateLabel("ShutdownPC", 406, 276, 67, 18, $SS_CENTERIMAGE)
$Label24 = GUICtrlCreateLabel("- shutdown your pc", 481, 276, 100, 18, $SS_CENTERIMAGE)
$Label25 = GUICtrlCreateLabel("SleepPC", 406, 290, 44, 18, $SS_CENTERIMAGE)
$Label26 = GUICtrlCreateLabel("- sleep your pc", 466, 290, 77, 18, $SS_CENTERIMAGE)
$Label27 = GUICtrlCreateLabel("RestartPC", 406, 304, 52, 18, $SS_CENTERIMAGE)
$Label28 = GUICtrlCreateLabel("- restart your pc", 466, 304, 83, 18, $SS_CENTERIMAGE)
$Label29 = GUICtrlCreateLabel("ScreenCapture", 406, 318, 77, 18, $SS_CENTERIMAGE)
$Label30 = GUICtrlCreateLabel("- capture computer's screen", 486, 318, 141, 18, $SS_CENTERIMAGE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlCreateTabItem("")
$bottomControlGroup = GUICtrlCreateGroup("Control", 8, 300, 282, 75)
$btnStart = GUICtrlCreateButton("Start Bot", 15, 320, 75, 50)
$btnStop = GUICtrlCreateButton("Stop Bot", 15, 347, 75, 23)
GUICtrlSetState(-1, $GUI_HIDE)
$btnHide = GUICtrlCreateButton("Hide BS", 110, 320, 75, 30)
$chkBackground = GUICtrlCreateCheckbox("BG Mode", 115, 355, 75, 15)
GUICtrlSetTip(-1, "Activate Background Mode")
$chkForceBS = GUICtrlCreateCheckbox("Force Active", 190, 355, 78, 15)
GUICtrlSetTip(-1, "Maximize Bluestack window if fail to locate")
$btnAtkNow = GUICtrlCreateButton("Attack Now", 190, 320, 75, 30)
$btnPause = GUICtrlCreateButton("Pause", 15, 320, 75, 23)
GUICtrlSetState(-1, $GUI_HIDE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$hPic_background = GUICtrlCreatePic("@ScriptDir\images\GUI\bannerfix.bmp", 0, 0, 640, 30)
Dim $frmBot_AccelTable[3][2] = [["{PGUP}", $menuItemExit],["{CAPS LOCK}", $menuItemDefault],["{F5}", $menuItemGreen]]
GUISetAccelerators($frmBot_AccelTable)
#EndRegion ### END Koda GUI section ###

; Add images
GUICtrlSetImage($imgGoldStart, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirStart, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkStart, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyStart, @ScriptDir & "\images\Resource\Trophy.jpg")
GUICtrlSetImage($imgGoldLast, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirLast, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkLast, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyLast, @ScriptDir & "\images\Resource\Trophy.jpg")
GUICtrlSetImage($imgGoldCurrent, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirCurrent, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkCurrent, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyCurrent, @ScriptDir & "\images\Resource\Trophy.jpg")
GUICtrlSetImage($imgGoldTotal, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirTotal, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkTotal, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyTotal, @ScriptDir & "\images\Resource\Trophy.jpg")

; Language events


; Define events
GUICtrlSetOnEvent($menuItemExit, "btnExit")
GUICtrlSetOnEvent($menuItemLoad, "btnLoadConfig")
GUICtrlSetOnEvent($menuItemSave, "btnSaveConfig")
GUICtrlSetOnEvent($menuItemNone, "btnTheme")
GUICtrlSetOnEvent($menuItemDefault, "btnTheme")
GUICtrlSetOnEvent($menuItemIron, "btnTheme")
GUICtrlSetOnEvent($menuItemSteel, "btnTheme")
GUICtrlSetOnEvent($menuItemGray, "btnTheme")
GUICtrlSetOnEvent($menuItemDark, "btnTheme")
GUICtrlSetOnEvent($menuItemBlack, "btnTheme")
GUICtrlSetOnEvent($menuItemAlloy, "btnTheme")
GUICtrlSetOnEvent($menuItemHex, "btnTheme")
GUICtrlSetOnEvent($menuItemCore, "btnTheme")
GUICtrlSetOnEvent($menuItemFresco, "btnTheme")
GUICtrlSetOnEvent($menuItemSoft, "btnTheme")
GUICtrlSetOnEvent($menuItemGreen, "btnTheme")
GUICtrlSetOnEvent($menuItemTeal, "btnTheme")
GUICtrlSetOnEvent($menuItemOrange, "btnTheme")
GUICtrlSetOnEvent($menuItemRed, "btnTheme")
GUICtrlSetOnEvent($tabMain, "tabMain")
GUICtrlSetOnEvent($btnStart, "btnStart")
GUICtrlSetOnEvent($btnStop, "btnStop")
GUICtrlSetOnEvent($btnPause, "btnPause")
GUICtrlSetOnEvent($btnHide, "btnHide")
GUICtrlSetOnEvent($chkBackground, "chkBackground")
GUICtrlSetOnEvent($chkForceBS, "chkForceBS")
GUICtrlSetOnEvent($btnAtkNow, "btnAtkNow")
GUICtrlSetOnEvent($btnLocateTownHall, "btnLocateTownHall")
GUICtrlSetOnEvent($btnLocateClanCastle2, "btnLocateClanCastle")
GUICtrlSetOnEvent($btnLocateKingAltar, "btnLocateKingAltar")
GUICtrlSetOnEvent($btnLocateQueenAltar, "btnLocateQueenAltar")
GUICtrlSetOnEvent($btnLocateDarkBarracks, "btnLocateDarkBarracks")
GUICtrlSetOnEvent($btnLocateBarracks, "btnLocateBarracks")
GUICtrlSetOnEvent($btnLocateSFactory, "btnLocateSFactory")
GUICtrlSetOnEvent($btnLocateCamp, "btnLocateCamp")
GUICtrlSetOnEvent($chkNoAttack, "chkNoAttack")
GUICtrlSetOnEvent($chkDonateOnly, "chkNoAttack")
GUICtrlSetOnEvent($btnSearchMode, "btnSearchMode")
GUICtrlSetOnEvent($chkRandomSpeedAtk, "Randomspeedatk")
GUICtrlSetOnEvent($btnFindWall, "btnFindWall")
GUICtrlSetOnEvent($btnLocateUp1, "btnLocateUp1")
GUICtrlSetOnEvent($btnLocateUp2, "btnLocateUp2")
GUICtrlSetOnEvent($btnLocateUp3, "btnLocateUp3")
GUICtrlSetOnEvent($btnCheckDefense, "btnCheckDefense")
GUICtrlSetOnEvent($chkPushMatchFound, "MatchFound")

; set title and icons
WinSetTitle("sBotTitle", "", $sBotTitle)
GUISetIcon(@ScriptDir & "Images\Icons\cocbot.ico")
TraySetIcon(@ScriptDir & "Images\Icons\cocbot.ico")

; add log text box
$txtLog = _GUICtrlRichEdit_Create($frmBot, "", 8, 68, 480, 185, BitOR($ES_MULTILINE, $ES_READONLY, $WS_VSCROLL, 8912))

; Add Banner
$hPic_background = GUICtrlCreatePic(@ScriptDir & "\images\GUI\bannerfix.bmp", 0, 0, 640, 30)
GUICtrlSetState($hPic_background, $GUI_DISABLE)

; Display Form
Func DisplayGUI()
	Opt("GUIOnEventMode", 1)
	GUISetState(@SW_SHOW, $frmBot)
	;Bottom status bar
	$statLog = _GUICtrlStatusBar_Create($frmBot)
	_GUICtrlStatusBar_SetSimple($statLog)
	_GUICtrlStatusBar_SetText($statLog, "Status : Idle")
	$tiAbout = TrayCreateItem("About")
	TrayCreateItem("")
	$tiExit = TrayCreateItem("Exit")
EndFunc
