#include <ButtonConstants.au3>
#include <ComboConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <TabConstants.au3>
#include <WindowsConstants.au3>
Opt("GUICloseOnESC", 0)
Opt("GUIOnEventMode", 1)
Opt("MouseClickDelay", 10)
Opt("MouseClickDownDelay", 10)
Opt("TrayMenuMode", 3)
#Region ### START Koda GUI section ### Form=GUI Form.kxf
$frmBot = GUICreate("sBotTitle", 646, 431, -1, -1)
$menuFile = GUICtrlCreateMenu("&File")
$menuItemExit = GUICtrlCreateMenuItem("E&xit", $menuFile)
$menuConfig = GUICtrlCreateMenu("&Config")
$menuItemLoad = GUICtrlCreateMenuItem("&Load", $menuConfig)
$menuItemSave = GUICtrlCreateMenuItem("&Save", $menuConfig)
$menuItemOptions = GUICtrlCreateMenuItem("&Options...", $menuConfig)
$menuHelp = GUICtrlCreateMenu("&Help")
$menuItemAbout = GUICtrlCreateMenuItem("&About", $menuHelp)
$tabMain = GUICtrlCreateTab(-1, 30, 645, 355)
$pageGeneral = GUICtrlCreateTabItem("General")
$groupLocationSettings = GUICtrlCreateGroup("Locate Buildings Manually", 488, 65, 140, 248)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$btnLocateTownHall = GUICtrlCreateButton("Locate Townhall", 503, 85, 110, 25)
$btnLocateClanCastle2 = GUICtrlCreateButton("Locate Clan Castle", 503, 113, 110, 25)
$btnLocateKingAltar = GUICtrlCreateButton("Locate King Altar", 503, 225, 110, 25)
$btnLocateQueenAltar = GUICtrlCreateButton("Locate Queen Altar", 503, 253, 110, 25)
$btnLocateDarkBarracks = GUICtrlCreateButton("Locate Dark Barrack", 503, 197, 110, 25)
$btnLocateBarracks = GUICtrlCreateButton("Locate Barracks", 503, 169, 110, 25)
$btnLocateSFactory = GUICtrlCreateButton("Locate Spell Factory", 503, 281, 110, 25)
$btnLocateCamp = GUICtrlCreateButton("Locate Army Camp", 503, 141, 110, 25)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupBottomOptions = GUICtrlCreateGroup("Options", 11, 255, 470, 43)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkBotStop = GUICtrlCreateCheckbox("", 26, 274, 16, 16)
$cmbBotCommand = GUICtrlCreateCombo("", 61, 270, 180, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Halt Attack Mode|Shutdown PC|Sleep PC", "Halt Attack Mode")
$lblPC = GUICtrlCreateLabel("IF :", 256, 273, 16, 17)
$cmbBotCond = GUICtrlCreateCombo("", 291, 270, 180, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "G and E Full and Max.Trophy|(G and E) Full or Max.Trophy|(G or E) Full and Max.Trophy|G or E Full or Max.Trophy|Gold and Elixir Full|Gold or Elixir Full|Gold Full and Max.Trophy|Elixir Full and Max.Trophy|Gold Full or Max.Trophy|Elixir Full or Max.Trophy|Gold Full|Elixir Full|Reach Max. Trophy", "Gold and Elixir Full")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupOtherOptions = GUICtrlCreateGroup("Other Options", 404, 314, 224, 60)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblMaxTrophy = GUICtrlCreateLabel("Trophy Range:", 419, 331, 72, 17)
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$txtMinimumTrophy = GUICtrlCreateInput("1800", 494, 327, 50, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 4)
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$lblMaxTrophy2 = GUICtrlCreateLabel("-", 554, 331, 5, 17)
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$txtMaxTrophy = GUICtrlCreateInput("2000", 569, 327, 50, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 4)
GUICtrlSetTip(-1, "When max trophies is reached, trophies will be dropped until below minimum setting")
$chkDonateOnly = GUICtrlCreateCheckbox("Donate Only", 536, 351, 75, 17)
GUICtrlSetTip(-1, "Disable attacking  training, only do collections/donating")
$chkNoAttack = GUICtrlCreateCheckbox("Donate/Train Only", 419, 351, 103, 17)
GUICtrlSetTip(-1, "Disable attacking, only do collections/training/donating")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageSearchSetting = GUICtrlCreateTabItem("Search")
$groupDeadConditions = GUICtrlCreateGroup("Dead Base Conditions", 28, 66, 250, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblDeadConditions = GUICtrlCreateLabel("Selected conditions must ALL be met when", 43, 89, 220, 15, $SS_CENTER)
$chkDeadGE = GUICtrlCreateCheckbox("Min Resources:", 43, 133, 100, 17)
$lblDeadMinGold = GUICtrlCreateLabel("Gold:", 148, 135, 28, 17)
$txtDeadMinGold = GUICtrlCreateInput("50000", 183, 131, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$cmbDead = GUICtrlCreateCombo("", 88, 156, 45, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "And|Or", "And")
$lblDeadMinElixir = GUICtrlCreateLabel("Elixir:", 148, 160, 28, 17)
$txtDeadMinElixir = GUICtrlCreateInput("50000", 183, 156, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$chkDeadMeetDE = GUICtrlCreateCheckbox("Min Dark Elixir:", 43, 183, 95, 17)
$txtDeadMinDarkElixir = GUICtrlCreateInput("0", 183, 181, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 4)
$chkDeadMeetTH = GUICtrlCreateCheckbox("Max TH Level:", 43, 233, 95, 17)
$cmbDeadTH = GUICtrlCreateCombo("", 183, 231, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "4-6|7|8|9|10", "4-6")
$chkDeadMeetTrophy = GUICtrlCreateCheckbox("Min Trophies:", 43, 208, 85, 17)
$txtDeadMinTrophy = GUICtrlCreateInput("0", 183, 206, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$chkDeadMeetTHO = GUICtrlCreateCheckbox("Townhall Outside", 43, 258, 100, 17)
$lblDeadConditions2 = GUICtrlCreateLabel("search base with full collectors", 43, 106, 220, 15, $SS_CENTER)
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlSetState(-1, $GUI_HIDE)
$groupAnyConditions = GUICtrlCreateGroup("Any Base Conditions", 313, 66, 250, 220)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblAnyConditions = GUICtrlCreateLabel("Selected conditions must ALL be met when", 328, 89, 220, 15, $SS_CENTER)
$chkMeetGE = GUICtrlCreateCheckbox("Min Resources:", 328, 133, 100, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
$lblMinGold = GUICtrlCreateLabel("Gold:", 433, 135, 28, 17)
$txtMinGold = GUICtrlCreateInput("80000", 468, 131, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$cmbAny = GUICtrlCreateCombo("", 373, 156, 45, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "And|Or", "And")
$lblMinElixir = GUICtrlCreateLabel("Elixir:", 433, 160, 28, 17)
$txtMinElixir = GUICtrlCreateInput("80000", 468, 156, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$chkMeetDE = GUICtrlCreateCheckbox("Min Dark Elixir:", 328, 183, 95, 17)
$txtMinDarkElixir = GUICtrlCreateInput("0", 468, 181, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 4)
$chkMeetTH = GUICtrlCreateCheckbox("Max TH Level:", 328, 233, 95, 17)
$cmbTH = GUICtrlCreateCombo("", 468, 231, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "4-6|7|8|9|10", "4-6")
$chkMeetTrophy = GUICtrlCreateCheckbox("Min Trophies:", 328, 208, 85, 17)
$txtMinTrophy = GUICtrlCreateInput("0", 468, 206, 60, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$chkMeetTHO = GUICtrlCreateCheckbox("Townhall Outside", 328, 258, 100, 17)
$lblAnyConditions2 = GUICtrlCreateLabel("search for any other base", 328, 106, 220, 15, $SS_CENTER)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupSearchOnly = GUICtrlCreateGroup("Search Only", 306, 299, 320, 75)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$btnSearchMode = GUICtrlCreateButton("Search Mode", 315, 337, 300, 30)
GUICtrlSetTip(-1, "Does not attack. Searches for base that meets conditions.")
$lblSearchOnly = GUICtrlCreateLabel("Searching only! Disables attacking!", 386, 317, 170, 18)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageAdvanceSetting = GUICtrlCreateTabItem("Adv Search")
$groupRedDead = GUICtrlCreateGroup("Dead Base Search Reduction", 13, 70, 200, 220)
$lblGoldRedDead = GUICtrlCreateLabel("Gold Reduce:", 23, 145, 70, 17)
$chkredDead = GUICtrlCreateCheckbox("Enable", 23, 95, 75, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Enable Search Reduction for Dead Base")
$txtGoldElixRedDead = GUICtrlCreateInput("5000", 143, 117, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 5)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtGoldRedDead = GUICtrlCreateInput("5000", 143, 142, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 5)
$txtElixRedDead = GUICtrlCreateInput("5000", 143, 167, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 5)
$txtDERedDead = GUICtrlCreateInput("100", 143, 192, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetLimit(-1, 4)
GUICtrlSetTip(-1, "Enter number of individual units to train")
$txtTroRedDead = GUICtrlCreateInput("2", 143, 217, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$txtRedSearchDead = GUICtrlCreateInput("20", 143, 242, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$lblElixRedDead = GUICtrlCreateLabel("Elixir Reduce:", 23, 170, 70, 17)
$lblDERedDead = GUICtrlCreateLabel("DE Reduce:", 23, 195, 70, 17)
$lblTroRedDead = GUICtrlCreateLabel("Trophy Reduce:", 23, 220, 85, 17)
$lblRedSearchDead = GUICtrlCreateLabel("After Search:", 23, 245, 70, 17)
$lblGoldElixRedDead = GUICtrlCreateLabel("Gold and Elixir Reduce:", 23, 120, 115, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$GroupRedAny = GUICtrlCreateGroup("Any Base Search Reduction", 223, 70, 200, 220)
$lblGoldRedAny = GUICtrlCreateLabel("Gold Reduce:", 233, 145, 70, 17)
$lblElixRedAny = GUICtrlCreateLabel("Elixir Reduce:", 233, 170, 70, 17)
$lblDERedAny = GUICtrlCreateLabel("DE Reduce:", 233, 195, 70, 17)
$lblTroRedAny = GUICtrlCreateLabel("Trophy Reduce:", 233, 220, 85, 17)
$lblRedSearchAny = GUICtrlCreateLabel("After Search:", 233, 245, 70, 17)
$chkredAny = GUICtrlCreateCheckbox("Enable", 233, 95, 75, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Enable Search Reduction for Any Base")
$txtGoldElixRedAny = GUICtrlCreateInput("5000", 353, 117, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 5)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblGoldElixRedAny = GUICtrlCreateLabel("Gold and Elixir Reduce:", 233, 120, 115, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtGoldRedAny = GUICtrlCreateInput("5000", 353, 142, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 5)
$txtElixRedAny = GUICtrlCreateInput("5000", 353, 167, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 5)
$txtDERedAny = GUICtrlCreateInput("100", 353, 192, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetLimit(-1, 4)
GUICtrlSetTip(-1, "Enter number of individual units to train")
$txtTroRedAny = GUICtrlCreateInput("2", 353, 217, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$txtRedSearchAny = GUICtrlCreateInput("20", 353, 242, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupAvoidDef = GUICtrlCreateGroup("Avoid Defend", 433, 72, 200, 220)
$chkInfTow = GUICtrlCreateCheckbox("Inferno Tower", 443, 97, 85, 15)
GUICtrlSetState(-1, $GUI_DISABLE)
$btnCheckDefense = GUICtrlCreateButton("Button 1", 443, 120, 75, 25)
GUICtrlSetState(-1, $GUI_HIDE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageAttackSettings = GUICtrlCreateTabItem("Attack")
$groupDeadDeploySettings = GUICtrlCreateGroup("Dead Base Deploy Settings", 11, 65, 610, 90)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$cmbDeadDeploy = GUICtrlCreateCombo("", 26, 87, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Attack on a single side, penetrates through base|Attack on two sides, penetrates through base|Attack on three sides, gets outer and some inside of base|Attack on all sides equally, gets most of outer base", "Attack on all sides equally, gets most of outer base")
$cmbDeadAlgorithm = GUICtrlCreateCombo("", 26, 122, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks|Use All Troops", "Use Barracks")
$chkDeadUseKing = GUICtrlCreateCheckbox("Attack with King", 341, 87, 102, 17)
$chkDeadUseQueen = GUICtrlCreateCheckbox("Attack with Queen", 341, 122, 110, 17)
$chkDeadUseClanCastle = GUICtrlCreateCheckbox("Attack with Clan Castle troops", 448, 87, 165, 17)
$cmbDeadAttackTH_vip = GUICtrlCreateCombo("", 456, 119, 145, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Don"&Chr(39)&"t attack TH|Limited TH attack|Full TH attack", "Don't attack TH")
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Troops can either not focus on townhall, send a single wave of archers and barbarians at the townhall, or focus all troops on townhall")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupAnyDeploySettings = GUICtrlCreateGroup("Other Base Deploy Settings", 11, 160, 610, 90)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$cmbDeploy = GUICtrlCreateCombo("", 26, 182, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Attack on a single side, penetrates through base|Attack on two sides, penetrates through base|Attack on three sides, gets outer and some inside of base|Attack on all sides equally, gets most of outer base", "Attack on all sides equally, gets most of outer base")
$cmbAlgorithm = GUICtrlCreateCombo("", 26, 217, 290, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks|Use All Troops", "Use Barracks")
$chkUseKing = GUICtrlCreateCheckbox("Attack with King", 341, 182, 102, 17)
$chkUseQueen = GUICtrlCreateCheckbox("Attack with Queen", 341, 217, 110, 17)
$chkUseClanCastle = GUICtrlCreateCheckbox("Attack with Clan Castle troops", 448, 182, 157, 17)
$cmbAttackTH_vip = GUICtrlCreateCombo("", 456, 214, 145, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Don"&Chr(39)&"t attack TH|Limited TH attack|Full TH attack", "Don't attack TH")
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Troops can either not focus on townhall, send a single wave of archers and barbarians at the townhall, or focus all troops on townhall")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupDeploySpeed = GUICtrlCreateGroup("Deploy Speed", 306, 262, 320, 110)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblUnitDelay = GUICtrlCreateLabel("Unit Delay:", 316, 292, 65, 17)
$cmbUnitDelay_vip = GUICtrlCreateCombo("", 386, 287, 50, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "1|2|3|4|5|6|7|8|9|10", "5")
GUICtrlSetState(-1, $GUI_DISABLE)
$lblWaveDelay = GUICtrlCreateLabel("Wave Delay:", 316, 322, 65, 17)
$cmbWaveDelay_vip = GUICtrlCreateCombo("", 386, 317, 50, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "1|2|3|4|5|6|7|8|9|10", "5")
GUICtrlSetState(-1, $GUI_DISABLE)
$chkRandomSpeedAtk_vip = GUICtrlCreateCheckbox("Random Speeds!!", 321, 345, 100, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblAttackDelay1 = GUICtrlCreateLabel("Delays for troop deployment", 440, 276, 180, 18, $SS_CENTER)
GUICtrlSetFont(-1, 9, 400, 4, "Arial")
$lblAttackDelay2 = GUICtrlCreateLabel("- [1] Fast = Bot Like!", 464, 293, 99, 18)
$lblAttackDelay3 = GUICtrlCreateLabel("- [10] Slow = Human Like!", 464, 309, 126, 18)
$lblAttackDelay4 = GUICtrlCreateLabel("Random will make bot more variant", 440, 333, 171, 18, $SS_CENTER)
$lblAttackDelay5 = GUICtrlCreateLabel("and closer to human!", 440, 350, 104, 18, $SS_CENTER)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageDonateSettings = GUICtrlCreateTabItem("Donate")
$groupBarbarians = GUICtrlCreateGroup("Option 1", 8, 57, 166, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDonateAllBarbarians = GUICtrlCreateCheckbox("Donate to All Request", 23, 73, 120, 15)
GUICtrlSetTip(-1, "Donate to all request regardless Donation Text")
$txtDonateBarbarians = GUICtrlCreateEdit("", 18, 107, 146, 111, BitOR($ES_AUTOVSCROLL,$ES_WANTRETURN,$WS_VSCROLL))
GUICtrlSetData(-1, StringFormat("any\r\nbarbarians\r\nreinforcement"))
GUICtrlSetTip(-1, "Keywords for option 1")
$cmbDonateBarbarians1 = GUICtrlCreateCombo("", 18, 222, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "Barbarian")
$cmbDonateBarbarians2 = GUICtrlCreateCombo("", 18, 246, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "None")
$cmbDonateBarbarians3 = GUICtrlCreateCombo("", 18, 270, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "None")
$NoOfBarbarians1 = GUICtrlCreateInput("5", 130, 222, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$NoOfBarbarians2 = GUICtrlCreateInput("1", 130, 246, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$NoOfBarbarians3 = GUICtrlCreateInput("1", 130, 270, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$chkDonateBarbarians = GUICtrlCreateCheckbox("Smart Donate", 23, 90, 82, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Donate Troop base on Setting and Donation Text")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupArchers = GUICtrlCreateGroup("Option 2", 176, 57, 166, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDonateAllArchers = GUICtrlCreateCheckbox("Donate to All Request", 191, 73, 120, 15)
GUICtrlSetTip(-1, "Donate to all request regardless Donation Text")
$txtDonateArchers = GUICtrlCreateEdit("", 186, 107, 146, 111, BitOR($ES_AUTOVSCROLL,$ES_WANTRETURN,$WS_VSCROLL))
GUICtrlSetData(-1, StringFormat("any\r\narchers\r\nreinforcement"))
GUICtrlSetTip(-1, "Keywords for option 2")
$cmbDonateArchers1 = GUICtrlCreateCombo("", 186, 222, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "Archer")
$cmbDonateArchers2 = GUICtrlCreateCombo("", 187, 246, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "None")
$cmbDonateArchers3 = GUICtrlCreateCombo("", 187, 270, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "None")
$NoOfArchers1 = GUICtrlCreateInput("5", 298, 222, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$NoOfArchers2 = GUICtrlCreateInput("1", 298, 246, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$NoOfArchers3 = GUICtrlCreateInput("1", 298, 270, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$chkDonateArchers = GUICtrlCreateCheckbox("Smart Donate", 191, 90, 82, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Donate Troop base on Setting and Donation Text")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupGiants = GUICtrlCreateGroup("Option 3", 344, 57, 166, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDonateAllGiants = GUICtrlCreateCheckbox("Donate to All Request", 359, 73, 120, 15)
GUICtrlSetTip(-1, "Donate to all request regardless Donation Text")
$txtDonateGiants = GUICtrlCreateEdit("", 354, 107, 146, 111, BitOR($ES_AUTOVSCROLL,$ES_WANTRETURN,$WS_VSCROLL))
GUICtrlSetData(-1, StringFormat("any\r\ngiants\r\nreinforcement"))
GUICtrlSetTip(-1, "Keywords for option 3")
$cmbDonateGiants1 = GUICtrlCreateCombo("", 354, 222, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "Giant")
$cmbDonateGiants2 = GUICtrlCreateCombo("", 354, 246, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "None")
$cmbDonateGiants3 = GUICtrlCreateCombo("", 354, 270, 89, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "None|Barbarian|Archer|Giant|Goblin|WallBreaker|Ballon|Wizard|Healer|Dragon|Pekka|Minion|Hog|Valkyrie|Golem|Witch|Lava", "None")
$NoOfGiants1 = GUICtrlCreateInput("5", 466, 222, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$NoOfGiants2 = GUICtrlCreateInput("1", 466, 246, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$NoOfGiants3 = GUICtrlCreateInput("1", 466, 270, 33, 22, BitOR($ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$chkDonateGiants = GUICtrlCreateCheckbox("Smart Donate", 359, 90, 82, 15)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Donate Troop base on Setting and Donation Text")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$chkRequest = GUICtrlCreateCheckbox("Request for :", 298, 312, 90, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetFont(-1, 9, 400, 0, "Arial")
$txtRequest = GUICtrlCreateInput("Any", 391, 310, 242, 23)
GUICtrlSetLimit(-1, 20)
GUICtrlSetFont(-1, 9, 400, 0, "Arial")
GUICtrlSetTip(-1, "Request for input.")
$groupNotDonate = GUICtrlCreateGroup("Donation Blacklist", 518, 57, 114, 242)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$txtNotDonate = GUICtrlCreateEdit("", 528, 98, 94, 190, BitOR($ES_AUTOVSCROLL,$ES_WANTRETURN,$WS_VSCROLL))
GUICtrlSetData(-1, StringFormat("cw\r\nclan war\r\nmax\r\nlevel\r\nlvl"))
GUICtrlSetTip(-1, "Blacklist Keywords")
$chkBlacklist = GUICtrlCreateCheckbox("Enable", 533, 75, 50, 14)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageTroopSettings = GUICtrlCreateTabItem("Troops")
$groupTroops = GUICtrlCreateGroup("Troops", 16, 60, 200, 240)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBarbarians = GUICtrlCreateLabel("Barb", 26, 85, 45, 17)
$lblArchers = GUICtrlCreateLabel("Archer", 26, 110, 45, 17)
$lblGoblins = GUICtrlCreateLabel("Goblin", 26, 135, 45, 17)
$txtBarbarians = GUICtrlCreateInput("30", 116, 82, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 3)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtArchers = GUICtrlCreateInput("60", 116, 107, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 3)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtGoblins = GUICtrlCreateInput("10", 116, 132, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 3)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblPercentBarbarians = GUICtrlCreateLabel("%", 176, 85, 12, 17)
$lblPercentArchers = GUICtrlCreateLabel("%", 176, 110, 12, 17)
$lblPercentGoblins = GUICtrlCreateLabel("%", 176, 134, 12, 17)
$lblGiants = GUICtrlCreateLabel("Giants :", 26, 160, 45, 17)
$lblWallBreakers = GUICtrlCreateLabel("Wall Breakers :", 26, 185, 85, 17)
$txtNumGiants = GUICtrlCreateInput("4", 116, 157, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Enter number of individual units to train")
$txtNumWallbreakers = GUICtrlCreateInput("4", 116, 182, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Enter number of individual units to train")
$lblCapacity = GUICtrlCreateLabel("Camp Capacity :", 26, 210, 85, 17)
$txtCapacity = GUICtrlCreateInput("0", 116, 207, 56, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 3)
$lblRaidcap = GUICtrlCreateLabel("Raid Capacity :", 26, 235, 85, 17)
$cmbRaidcap = GUICtrlCreateCombo("", 116, 232, 56, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "10|20|30|40|50|60|70|80|90|100", "100")
$lblPercentCapacity = GUICtrlCreateLabel("%", 176, 235, 12, 17)
$cmbTroopComp = GUICtrlCreateCombo("", 26, 264, 175, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|B.Arch|B.A.G.G.|B.A.Giant|B.A.Goblin|B.A.G.G.Wall|Use Barracks|Custom Troops|Custom Troops 2", "Use Barracks")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupCustomTroops2 = GUICtrlCreateGroup("Custom Troops 2", 236, 60, 395, 121)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBarrackJOE1 = GUICtrlCreateLabel("Barrack 1 :", 246, 79, 53, 17)
$lblBarrackJOE2 = GUICtrlCreateLabel("Barrack 2 :", 246, 104, 53, 17)
$lblBarrackJOE3 = GUICtrlCreateLabel("Barrack 3 :", 246, 129, 53, 17)
$lblBarrackJOE4 = GUICtrlCreateLabel("Barrack 4 :", 246, 154, 53, 17)
$lblBarrackBK1 = GUICtrlCreateLabel("the rest", 451, 79, 40, 17)
$lblBarrackBK2 = GUICtrlCreateLabel("the rest", 451, 104, 40, 17)
$lblBarrackBK3 = GUICtrlCreateLabel("the rest", 451, 129, 40, 17)
$lblBarrackBK4 = GUICtrlCreateLabel("the rest", 451, 154, 40, 17)
$txtFirstTroop1 = GUICtrlCreateInput("2", 306, 76, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtFirstTroop2 = GUICtrlCreateInput("2", 306, 101, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtFirstTroop3 = GUICtrlCreateInput("2", 306, 126, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtFirstTroop4 = GUICtrlCreateInput("2", 306, 151, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbFirstTroop1 = GUICtrlCreateCombo("", 346, 76, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing", "W.Breakers")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbFirstTroop2 = GUICtrlCreateCombo("", 346, 101, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing", "W.Breakers")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbFirstTroop3 = GUICtrlCreateCombo("", 346, 126, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing", "Giants")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbFirstTroop4 = GUICtrlCreateCombo("", 346, 151, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Nothing", "Giants")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbSecondTroop1 = GUICtrlCreateCombo("", 501, 76, 95, 25, BitOR($CBS_DROPDOWNLIST,$CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing", "Barbarians")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbSecondTroop2 = GUICtrlCreateCombo("", 501, 101, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing", "Archers")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbSecondTroop3 = GUICtrlCreateCombo("", 501, 126, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing", "Barbarians")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbSecondTroop4 = GUICtrlCreateCombo("", 501, 151, 95, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|Balloons|Wizards|Nothing", "Archers")
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupBarracks = GUICtrlCreateGroup("Barracks", 236, 180, 185, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBarrack1 = GUICtrlCreateLabel("Barrack 1:", 246, 200, 53, 17)
$lblBarrack2 = GUICtrlCreateLabel("Barrack 2:", 246, 225, 53, 17)
$lblBarrack3 = GUICtrlCreateLabel("Barrack 3:", 247, 250, 53, 17)
$lblBarrack4 = GUICtrlCreateLabel("Barrack 4:", 247, 275, 53, 17)
$cmbBarrack1 = GUICtrlCreateCombo("", 301, 196, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Barbarians")
$cmbBarrack2 = GUICtrlCreateCombo("", 301, 221, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Archers")
$cmbBarrack3 = GUICtrlCreateCombo("", 302, 246, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Archers")
$cmbBarrack4 = GUICtrlCreateCombo("", 302, 271, 110, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breakers|Balloon|Wizard|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Archers")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupDarkTroops = GUICtrlCreateGroup("Dark Troops", 426, 180, 204, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkDarkTroop = GUICtrlCreateCheckbox("Enabled", 438, 202, 80, 15)
$lblDarkBarrack1 = GUICtrlCreateLabel("Dark Barrack 1:", 436, 228, 80, 17)
$lblDarkBarrack2 = GUICtrlCreateLabel("Dark Barrack 2:", 436, 259, 80, 17)
$cmbDarkBarrack1 = GUICtrlCreateCombo("", 551, 224, 70, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Minions|Hogs|Valkyries|Nothing", "Minions")
$cmbDarkBarrack2 = GUICtrlCreateCombo("", 551, 255, 70, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Minions|Hogs|Valkyries|Nothing", "Minions")
$txtDarkBarrack1 = GUICtrlCreateInput("5", 516, 224, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$txtDarkBarrack2 = GUICtrlCreateInput("5", 516, 255, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageUpgradeSettings = GUICtrlCreateTabItem("Upgrades")
$groupWalls = GUICtrlCreateGroup("Walls", 16, 65, 470, 125)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkWalls_vip = GUICtrlCreateCheckbox("Auto Wall Upgrade", 26, 87, 110, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$UseGold_vip = GUICtrlCreateRadio("Use Only Gold", 36, 112, 115, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblWallMinGold = GUICtrlCreateLabel("Minimum Gold:", 286, 142, 76, 17)
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform the upgrade")
$txtWallMinGold_vip = GUICtrlCreateInput("1300000", 406, 137, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 7)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform the upgrade")
$UseElixir_vip = GUICtrlCreateRadio("Use Only Elixir", 36, 137, 115, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblWallMinElixir = GUICtrlCreateLabel("Minimum Elixir:", 286, 167, 72, 17)
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform the upgrade")
$txtWallMinElixir_vip = GUICtrlCreateInput("1300000", 406, 162, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 7)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform the upgrade")
$UseGoldElix_vip = GUICtrlCreateRadio("Use Gold and then Elixir", 36, 162, 150, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblWalls = GUICtrlCreateLabel("Current Wall Level:", 286, 89, 100, 17)
$cmbWalls_vip = GUICtrlCreateCombo("", 406, 85, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "4|5|6|7|8|9|10", "4")
GUICtrlSetState(-1, $GUI_DISABLE)
$lblTolerance = GUICtrlCreateLabel("Tolerance Level:", 286, 117, 80, 17)
$cmbTolerance_vip = GUICtrlCreateCombo("", 406, 112, 60, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "Default|Lower|Higher", "Default")
GUICtrlSetState(-1, $GUI_DISABLE)
$btnFindWall_vip = GUICtrlCreateButton("Find Wall", 141, 85, 63, 21)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupUpgrade = GUICtrlCreateGroup("Buildings / Walls Upgrade", 16, 190, 470, 105)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$chkUpgrade1_vip = GUICtrlCreateCheckbox("Upgrade 1 :", 26, 207, 80, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblUP1PosX = GUICtrlCreateLabel("Pos X :", 108, 209, 35, 17)
$txtUpgradeX1_vip = GUICtrlCreateInput("", 148, 204, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$lblUP1PosY = GUICtrlCreateLabel("Pos Y :", 191, 209, 35, 17)
$txtUpgradeY1_vip = GUICtrlCreateInput("", 231, 204, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$btnLocateUp1_vip = GUICtrlCreateButton("Locate Building 1", 281, 204, 100, 21)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkUpgrade2_vip = GUICtrlCreateCheckbox("Upgrade 2 :", 26, 237, 80, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblUP2PosX = GUICtrlCreateLabel("Pos X :", 108, 239, 35, 17)
$txtUpgradeX2_vip = GUICtrlCreateInput("", 148, 234, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$lblUP2PosY = GUICtrlCreateLabel("Pos Y :", 191, 239, 35, 17)
$txtUpgradeY2_vip = GUICtrlCreateInput("", 231, 234, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$btnLocateUp2_vip = GUICtrlCreateButton("Locate Building 2", 281, 234, 100, 21)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkUpgrade3_vip = GUICtrlCreateCheckbox("Upgrade 3 :", 26, 267, 80, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblUP3PosX = GUICtrlCreateLabel("Pos X :", 108, 269, 35, 17)
$txtUpgradeX3_vip = GUICtrlCreateInput("", 148, 264, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$lblUP3PosY = GUICtrlCreateLabel("Pos Y :", 191, 269, 35, 17)
$txtUpgradeY3_vip = GUICtrlCreateInput("", 231, 264, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_READONLY,$ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$btnLocateUp3_vip = GUICtrlCreateButton("Locate Building 3", 281, 264, 100, 21)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblBldgMinGold = GUICtrlCreateLabel("Minimum Gold:", 396, 204, 76, 17)
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform building upgrade")
$lblBldgMinElixir = GUICtrlCreateLabel("Minimum Elixir:", 396, 248, 72, 17)
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform building upgrade")
$txtBldgMinGold_vip = GUICtrlCreateInput("1300000", 401, 222, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 7)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Minimum level of Gold storage to perform Building upgrade")
$txtBldgMinElixir_vip = GUICtrlCreateInput("1300000", 401, 266, 61, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 7)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Minimum level of Elixir storage to perform Building upgrade")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupBoosts = GUICtrlCreateGroup("Boosts", 493, 65, 130, 310)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblBoostBarracks = GUICtrlCreateLabel("Boosts left :", 503, 89, 60, 17)
$cmbBoostBarracks_vip = GUICtrlCreateCombo("", 573, 85, 40, 25, BitOR($GUI_SS_DEFAULT_COMBO,$CBS_SIMPLE))
GUICtrlSetData(-1, "0|1|2|3|4|5|6|7|8|9|10", "0")
$chkBoostKing_vip = GUICtrlCreateCheckbox("King Altar", 503, 115, 65, 17)
$chkBoostQueen_vip = GUICtrlCreateCheckbox("Queen Altar", 503, 140, 75, 17)
$chkBoostRax1_vip = GUICtrlCreateCheckbox("Barrack 1", 503, 165, 65, 17)
$chkBoostRax2_vip = GUICtrlCreateCheckbox("Barrack 2", 503, 190, 65, 17)
$chkBoostRax3_vip = GUICtrlCreateCheckbox("Barrack 3", 503, 215, 65, 17)
$chkBoostRax4_vip = GUICtrlCreateCheckbox("Barrack 4", 503, 240, 65, 17)
$chkBoostDark1_vip = GUICtrlCreateCheckbox("Dark Barrack 1", 503, 265, 90, 17)
$chkBoostDark2_vip = GUICtrlCreateCheckbox("Dark Barrack 2", 503, 290, 90, 17)
$chkBoostSpell_vip = GUICtrlCreateCheckbox("Spell Factory", 503, 315, 80, 17)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageMiscSettings = GUICtrlCreateTabItem("Misc")
$groupMiscs = GUICtrlCreateGroup("Misc", 16, 65, 600, 235)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblReconnect = GUICtrlCreateLabel("Reconnect Interval:", 26, 85, 98, 17)
GUICtrlSetTip(-1, "Set reconnect interval when other devices connected - COC English version Only")
$txtReconnect = GUICtrlCreateInput("2", 126, 81, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$lblReconnectmin = GUICtrlCreateLabel("minutes", 161, 85, 42, 17)
$chkTrap = GUICtrlCreateCheckbox("Auto Rearm Traps", 171, 247, 110, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Auto rearm for Traps, Crossbows  Inferno Towers")
$lblSearchsp = GUICtrlCreateLabel("Seach Base Speed:", 26, 112, 98, 17)
GUICtrlSetTip(-1, "Set search base speed to higher number if having frequent server sync issue")
$lblSearchspd = GUICtrlCreateLabel("Tips: 0 = Fast, 9 = Slow", 161, 112, 120, 17)
$UseSkillTimed = GUICtrlCreateRadio("King Skill Delay:", 26, 140, 95, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Set delay timing for King skill")
$txtKingSkill = GUICtrlCreateInput("10", 126, 136, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$lblKingsSkill = GUICtrlCreateLabel("seconds   /", 161, 140, 60, 17)
$lblQueenSkill = GUICtrlCreateLabel("Queen Skill Delay:", 226, 140, 88, 17)
GUICtrlSetTip(-1, "Set delay timing for Queen skill")
$txtQueenSkill = GUICtrlCreateInput("10", 316, 136, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$lblQueensSkill = GUICtrlCreateLabel("seconds", 351, 140, 45, 17)
$lblReturnh = GUICtrlCreateLabel("Return Home Delay:", 26, 193, 98, 17)
GUICtrlSetTip(-1, "Set delay timing for return home during raid")
$txtReturnh = GUICtrlCreateInput("10", 126, 189, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$lblReturndelay = GUICtrlCreateLabel("seconds after No Income", 161, 193, 125, 17)
$chkSpellDarkStorage_vip = GUICtrlCreateCheckbox("Cast Lightning when left:", 26, 219, 137, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Set Min Dark Elixir to Lightning Dark Storage")
$txtSpellDarkStorage_vip = GUICtrlCreateInput("500", 166, 215, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 4)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblSpellDarkStorage = GUICtrlCreateLabel("Dark Elixir", 201, 220, 50, 17)
$chkTakeTownSS = GUICtrlCreateCheckbox("Take All Towns Snapshot", 466, 275, 141, 17)
$chkTakeLootSS = GUICtrlCreateCheckbox("Take Loots Snapshot", 316, 275, 118, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
$chkAlertSearch = GUICtrlCreateCheckbox("Base Found Alert", 171, 275, 100, 17)
$UseSkillAuto_vip = GUICtrlCreateRadio("Auto Activate Heroes Skill on Low Health", 26, 166, 215, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Skill will activate when hero's health is low")
$chkRaxRestart = GUICtrlCreateCheckbox("Restart Bluestack if Fail to Locate All 4 Barracks", 316, 84, 250, 17)
GUICtrlSetTip(-1, "Restart bluestack if fail to detect all 4 barracks")
$chkMultiLight_vip = GUICtrlCreateCheckbox("Smart Lightning Spell", 316, 219, 120, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Cast Lightning as long as Dark Elixir more than Min requirement")
$chkkeeplogs = GUICtrlCreateCheckbox("Keep Logs:", 26, 275, 70, 17)
GUICtrlSetTip(-1, "Set number of logs you want to keep")
$txtkeeplogs = GUICtrlCreateInput("20", 101, 271, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 3)
$chkWideEdge = GUICtrlCreateCheckbox("Search Deeper Townhall", 316, 247, 136, 17)
GUICtrlSetTip(-1, "Increase the range for Townhall to be considering as Outside")
$chkRedLine_vip = GUICtrlCreateCheckbox("Attack Near Red Line", 466, 247, 120, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Look for red line and deploy troops near them")
$txtSearchsp = GUICtrlCreateInput("3", 126, 108, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 1)
$txtwhitecloud = GUICtrlCreateInput("30", 446, 108, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$Label22 = GUICtrlCreateLabel("seconds", 481, 112, 45, 17)
$lblwhitecloud = GUICtrlCreateLabel("White Cloud Waiting Time:", 316, 112, 128, 17)
GUICtrlSetTip(-1, "Set waiting time for next base when searching")
$chkCollect = GUICtrlCreateCheckbox("Auto Collect Resource", 26, 247, 125, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
GUICtrlSetTip(-1, "Auto Collect All Available Resource")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageStatsSetting = GUICtrlCreateTabItem("Stats")
$groupResourceAtStart = GUICtrlCreateGroup("Resources at Start", 16, 65, 185, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldonstart = GUICtrlCreateLabel("Gold at Start :", 46, 93, 75, 17)
$lblresultgoldtstart = GUICtrlCreateLabel("0", 126, 93, 60, 17, $SS_RIGHT)
$imgGoldStart = GUICtrlCreatePic("", 26, 93, 15, 15)
$lblelixironstart = GUICtrlCreateLabel("Elixir at Start :", 46, 113, 75, 17)
$lblresultelixirstart = GUICtrlCreateLabel("0", 126, 113, 60, 17, $SS_RIGHT)
$imgElixirStart = GUICtrlCreatePic("", 26, 113, 15, 15)
$lbldeonstart = GUICtrlCreateLabel("DE at Start :", 46, 133, 75, 17)
$lblresultdestart = GUICtrlCreateLabel("0", 126, 133, 60, 17, $SS_RIGHT)
$imgDarkStart = GUICtrlCreatePic("", 26, 133, 15, 15)
$lbltrophyonstart = GUICtrlCreateLabel("Trophies at Start :", 46, 153, 90, 17)
$lblresulttrophystart = GUICtrlCreateLabel("0", 141, 153, 45, 17, $SS_RIGHT)
$imgTrophyStart = GUICtrlCreatePic("", 26, 153, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupOtherStats = GUICtrlCreateGroup("Other Stats", 433, 65, 185, 230)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblvillagesattacked = GUICtrlCreateLabel("Attacked :", 443, 89, 80, 17)
$lblresultvillagesattacked = GUICtrlCreateLabel("0", 543, 89, 60, 17, $SS_RIGHT)
$lblvillagesskipped = GUICtrlCreateLabel("Skipped :", 443, 109, 80, 17)
$lblresultvillagesskipped = GUICtrlCreateLabel("0", 543, 109, 60, 17, $SS_RIGHT)
$lblwallupgrade = GUICtrlCreateLabel("Wall Upgrades :", 443, 129, 80, 17)
$lblwallupgradecount = GUICtrlCreateLabel("0", 543, 129, 60, 17, $SS_RIGHT)
$lblsearchcost = GUICtrlCreateLabel("Search Cost :", 443, 149, 80, 17)
$lblresultsearchcost = GUICtrlCreateLabel("0", 543, 149, 60, 17, $SS_RIGHT)
$lblbuilder = GUICtrlCreateLabel("Builder :", 443, 169, 80, 17)
$lblresultbuilder = GUICtrlCreateLabel("0", 543, 169, 60, 17, $SS_RIGHT)
$lblruntime = GUICtrlCreateLabel("Bot Run Time :", 443, 269, 80, 17)
$lblresultruntime = GUICtrlCreateLabel("00:00:00", 543, 269, 60, 17, $SS_RIGHT)
$lbloos = GUICtrlCreateLabel("Disconnect :", 443, 189, 80, 17)
$lblresultoos = GUICtrlCreateLabel("0", 543, 189, 60, 17, $SS_RIGHT)
$lblgoldperhour = GUICtrlCreateLabel("Gold / Hour :", 443, 209, 80, 18)
$lblelixirperhour = GUICtrlCreateLabel("Elixir / Hour :", 443, 229, 80, 18)
$lblresultgph = GUICtrlCreateLabel("0", 543, 209, 60, 18, $SS_RIGHT)
$lblresulteph = GUICtrlCreateLabel("0", 543, 229, 60, 18, $SS_RIGHT)
$lbldeperhour = GUICtrlCreateLabel("DE / Hour :", 443, 249, 80, 18)
$lblresultdeph = GUICtrlCreateLabel("0", 543, 249, 60, 18, $SS_RIGHT)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupLastRaid = GUICtrlCreateGroup("Last Raid Loot", 16, 185, 185, 110)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldlast = GUICtrlCreateLabel("Gold Loot:", 46, 210, 60, 17)
$lblresultgoldlast = GUICtrlCreateLabel("0", 124, 210, 60, 17, $SS_RIGHT)
$imgGoldLast = GUICtrlCreatePic("", 26, 210, 15, 15)
$lblelixirlast = GUICtrlCreateLabel("Elixir Loot:", 46, 230, 60, 17)
$lblresultelixirlast = GUICtrlCreateLabel("0", 124, 230, 60, 17, $SS_RIGHT)
$imgElixirLast = GUICtrlCreatePic("", 26, 230, 15, 15)
$lbldelast = GUICtrlCreateLabel("DE Loot:", 46, 250, 60, 17)
$lblresultdelast = GUICtrlCreateLabel("0", 124, 250, 60, 17, $SS_RIGHT)
$imgDarkLast = GUICtrlCreatePic("", 26, 250, 15, 15)
$lbltrophylast = GUICtrlCreateLabel("Trophies Won :", 46, 270, 75, 17)
$lblresulttrophylast = GUICtrlCreateLabel("0", 124, 270, 60, 17, $SS_RIGHT)
$imgTrophyLast = GUICtrlCreatePic("", 26, 270, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupCurrentResources = GUICtrlCreateGroup("Current Resources", 223, 65, 185, 120)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldnow = GUICtrlCreateLabel("Gold Now :", 253, 93, 75, 17)
$lblresultgoldnow = GUICtrlCreateLabel("0", 333, 93, 60, 17, $SS_RIGHT)
$imgGoldCurrent = GUICtrlCreatePic("", 233, 93, 15, 15)
$lblelixirnow = GUICtrlCreateLabel("Elixir Now :", 253, 113, 75, 17)
$lblresultelixirnow = GUICtrlCreateLabel("0", 333, 113, 60, 17, $SS_RIGHT)
$imgElixirCurrent = GUICtrlCreatePic("", 233, 113, 15, 15)
$lbldenow = GUICtrlCreateLabel("DE Now :", 253, 133, 75, 17)
$lblresultdenow = GUICtrlCreateLabel("0", 333, 133, 60, 17, $SS_RIGHT)
$imgDarkCurrent = GUICtrlCreatePic("", 233, 133, 15, 15)
$lbltrophynow = GUICtrlCreateLabel("Trophies Now :", 253, 153, 75, 17)
$lblresulttrophynow = GUICtrlCreateLabel("0", 333, 153, 60, 17, $SS_RIGHT)
$imgTrophyCurrent = GUICtrlCreatePic("", 233, 153, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupTotalRaid = GUICtrlCreateGroup("Total Loot", 223, 185, 185, 110)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblgoldgain = GUICtrlCreateLabel("Gold Gain :", 253, 208, 75, 17)
$lblresultgoldgain = GUICtrlCreateLabel("0", 333, 208, 60, 17, $SS_RIGHT)
$imgGoldTotal = GUICtrlCreatePic("", 233, 208, 15, 15)
$lblelixirgain = GUICtrlCreateLabel("Elixir Gain :", 253, 228, 75, 17)
$lblresultelixirgain = GUICtrlCreateLabel("0", 333, 228, 60, 17, $SS_RIGHT)
$imgElixirTotal = GUICtrlCreatePic("", 233, 228, 15, 15)
$lbldegain = GUICtrlCreateLabel("DE Gain :", 253, 248, 75, 17)
$lblresultdegain = GUICtrlCreateLabel("0", 333, 248, 60, 17, $SS_RIGHT)
$imgDarkTotal = GUICtrlCreatePic("", 233, 248, 15, 15)
$lbltrophiesdropped = GUICtrlCreateLabel("Trophies Won :", 253, 268, 75, 17)
$lblresulttrophiesdropped = GUICtrlCreateLabel("0", 333, 268, 60, 17, $SS_RIGHT)
$imgTrophyTotal = GUICtrlCreatePic("", 233, 268, 15, 15)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$pageNotificationSetting = GUICtrlCreateTabItem("Notification")
$groupPushBullet = GUICtrlCreateGroup("PushBullet", 8, 65, 375, 231)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$lblPushBulletToken = GUICtrlCreateLabel("Account Token:", 18, 115, 80, 17, $SS_CENTER)
$txtPushBulletTokenValue_vip = GUICtrlCreateInput("", 108, 115, 260, 22)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkPushBulletEnabled_vip = GUICtrlCreateCheckbox("Enable", 18, 90, 60, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Enable pushbullet notification")
$chkPushBulletDebug_vip = GUICtrlCreateCheckbox("Debug", 88, 90, 60, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "This will add verbosity on log while sending files via pushbullet")
$chkPushBulletRemote_vip = GUICtrlCreateCheckbox("Remote", 158, 90, 60, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Enables pushbullet remote function")
$chkPushBulletDelete_vip = GUICtrlCreateCheckbox("Delete All Msg on Start", 228, 90, 128, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Will delete all messages when bot starts")
$groupPushMessages = GUICtrlCreateGroup("Push Messages", 18, 140, 260, 67)
$chkPushVillageReport_vip = GUICtrlCreateCheckbox("Village Report", 28, 162, 90, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkPushMatchFound_vip = GUICtrlCreateCheckbox("Match Found", 28, 179, 90, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkPushLastRaid_vip = GUICtrlCreateCheckbox("Last Raid", 118, 162, 70, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkPushTotalRaid_vip = GUICtrlCreateCheckbox("Total Raid", 118, 179, 70, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkPushFreeBuilder_vip = GUICtrlCreateCheckbox("Free Builder", 191, 162, 75, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
$chkPushError_vip = GUICtrlCreateCheckbox("Errors", 192, 179, 70, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupPushLastRaid = GUICtrlCreateGroup("Last Raid", 288, 140, 80, 67)
$UsePushJPG_vip = GUICtrlCreateRadio("as JPG", 298, 162, 60, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Attach the loot jpg file in push message")
$UsePushText_vip = GUICtrlCreateRadio("as TXT", 298, 179, 60, 17)
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlSetTip(-1, "Push only text message")
GUICtrlCreateGroup("", -99, -99, 1, 1)
$groupRemoteConfig = GUICtrlCreateGroup("Misc.", 208, 209, 161, 75)
$lblPushBulletInterval = GUICtrlCreateLabel("Check Interval:", 218, 234, 82, 17)
$txtPushBulletInterval_vip = GUICtrlCreateInput("10", 303, 229, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblPushBulletIntervalMin = GUICtrlCreateLabel("mins", 338, 234, 29, 17)
$txtPushBulletMessages_vip = GUICtrlCreateInput("100", 303, 254, 31, 22, BitOR($GUI_SS_DEFAULT_INPUT,$ES_CENTER,$ES_NUMBER))
GUICtrlSetLimit(-1, 3)
GUICtrlSetState(-1, $GUI_DISABLE)
$lblPushBulletMessages = GUICtrlCreateLabel("Keep Messages:", 218, 259, 82, 17)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$Group2 = GUICtrlCreateGroup("PushBullet Settings", 16, 209, 185, 75)
$Label31 = GUICtrlCreateLabel("Device:", 24, 243, 40, 18)
$cmbPushDevice_vip = GUICtrlCreateCombo("All", 70, 240, 121, 25, BitOR($CBS_DROPDOWN,$CBS_AUTOHSCROLL))
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlCreateGroup("", -99, -99, 1, 1)
$Group1 = GUICtrlCreateGroup("Help", 400, 64, 233, 289)
GUICtrlSetFont(-1, 8, 400, 0, "Arial")
$Label2 = GUICtrlCreateLabel("You can remotely control your bot using", 410, 85, 197, 18, $SS_CENTERIMAGE)
$Label3 = GUICtrlCreateLabel("the following command format", 410, 99, 149, 18, $SS_CENTERIMAGE)
$Label4 = GUICtrlCreateLabel("Bot <command> where <command> is:", 410, 122, 191, 18, $SS_CENTERIMAGE)
$Label5 = GUICtrlCreateLabel("Pause", 410, 146, 34, 18, $SS_CENTERIMAGE)
$Label6 = GUICtrlCreateLabel("Resume", 410, 161, 43, 18, $SS_CENTERIMAGE)
$Label7 = GUICtrlCreateLabel("Stats", 410, 176, 29, 18, $SS_CENTERIMAGE)
$Label8 = GUICtrlCreateLabel("Logs", 410, 191, 28, 18, $SS_CENTERIMAGE)
$Label9 = GUICtrlCreateLabel("Boost1", 410, 206, 38, 18, $SS_CENTERIMAGE)
$Label10 = GUICtrlCreateLabel("Boost2", 410, 221, 38, 18, $SS_CENTERIMAGE)
$Label11 = GUICtrlCreateLabel("Boost3", 410, 237, 38, 18, $SS_CENTERIMAGE)
$Label12 = GUICtrlCreateLabel("BoostAll", 410, 251, 44, 18, $SS_CENTERIMAGE)
$Label13 = GUICtrlCreateLabel("Help", 410, 265, 25, 18, $SS_CENTERIMAGE)
$Label1 = GUICtrlCreateLabel("- pause the bot", 470, 146, 77, 18, $SS_CENTERIMAGE)
$Label14 = GUICtrlCreateLabel("- send this help message", 470, 265, 125, 18, $SS_CENTERIMAGE)
$Label15 = GUICtrlCreateLabel("- Boost all barracks", 470, 251, 98, 18, $SS_CENTERIMAGE)
$Label16 = GUICtrlCreateLabel("- Boost 3 barracks", 470, 237, 94, 18, $SS_CENTERIMAGE)
$Label17 = GUICtrlCreateLabel("- Boost 2 barracks", 470, 221, 94, 18, $SS_CENTERIMAGE)
$Label18 = GUICtrlCreateLabel("- Boost 1 barrack", 470, 206, 88, 18, $SS_CENTERIMAGE)
$Label19 = GUICtrlCreateLabel("- send the current log file", 470, 191, 125, 18, $SS_CENTERIMAGE)
$Label20 = GUICtrlCreateLabel("- send bot current statistics", 470, 176, 137, 18, $SS_CENTERIMAGE)
$Label21 = GUICtrlCreateLabel("- resume the bot", 470, 161, 83, 18, $SS_CENTERIMAGE)
$Label23 = GUICtrlCreateLabel("ShutdownPC", 410, 279, 67, 18, $SS_CENTERIMAGE)
$Label24 = GUICtrlCreateLabel("- shutdown your pc", 485, 279, 100, 18, $SS_CENTERIMAGE)
$Label25 = GUICtrlCreateLabel("SleepPC", 410, 293, 44, 18, $SS_CENTERIMAGE)
$Label26 = GUICtrlCreateLabel("- sleep your pc", 470, 293, 77, 18, $SS_CENTERIMAGE)
$Label27 = GUICtrlCreateLabel("RestartPC", 410, 307, 52, 18, $SS_CENTERIMAGE)
$Label28 = GUICtrlCreateLabel("- restart your pc", 470, 307, 83, 18, $SS_CENTERIMAGE)
$Label29 = GUICtrlCreateLabel("ScreenCapture", 410, 321, 77, 18, $SS_CENTERIMAGE)
$Label30 = GUICtrlCreateLabel("- capture computer's screen", 490, 321, 141, 18, $SS_CENTERIMAGE)
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlCreateTabItem("")
GUICtrlSetState(-1, $GUI_HIDE)
$bottomControlGroup = GUICtrlCreateGroup("Control", 8, 300, 282, 75)
$btnPause = GUICtrlCreateButton("Pause", 15, 320, 75, 23)
GUICtrlSetState(-1, $GUI_HIDE)
$btnStop = GUICtrlCreateButton("Stop Bot", 15, 347, 75, 23)
GUICtrlSetState(-1, $GUI_HIDE)
$btnStart = GUICtrlCreateButton("Start Bot", 15, 320, 75, 50)
$btnHide = GUICtrlCreateButton("Hide BS", 110, 320, 75, 30)
$btnAtkNow = GUICtrlCreateButton("Attack Now", 190, 320, 75, 30)
$chkBackground = GUICtrlCreateCheckbox("BG Mode", 115, 355, 63, 15)
GUICtrlSetTip(-1, "Activate Background Mode")
$chkForceBS = GUICtrlCreateCheckbox("Force Active", 190, 355, 78, 15)
GUICtrlSetTip(-1, "Maximize Bluestack window if fail to locate")
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###


; Add images
GUICtrlSetImage($imgGoldStart, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirStart, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkStart, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyStart, @ScriptDir & "\images\Resource\Trophy.jpg")
GUICtrlSetImage($imgGoldLast, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirLast, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkLast, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyLast, @ScriptDir & "\images\Resource\Trophy.jpg")
GUICtrlSetImage($imgGoldCurrent, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirCurrent, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkCurrent, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyCurrent, @ScriptDir & "\images\Resource\Trophy.jpg")
GUICtrlSetImage($imgGoldTotal, @ScriptDir & "\images\Resource\Gold.jpg")
GUICtrlSetImage($imgElixirTotal, @ScriptDir & "\images\Resource\Elixir.jpg")
GUICtrlSetImage($imgDarkTotal, @ScriptDir & "\images\Resource\Dark.jpg")
GUICtrlSetImage($imgTrophyTotal, @ScriptDir & "\images\Resource\Trophy.jpg")


; Define events
GUICtrlSetOnEvent($menuItemExit, "btnExit")
GUICtrlSetOnEvent($menuItemLoad, "btnLoadConfig")
GUICtrlSetOnEvent($menuItemSave, "btnSaveConfig")
GUICtrlSetOnEvent($menuItemOptions, "btnOptions")
GUICtrlSetOnEvent($menuItemAbout, "btnAbout")
GUICtrlSetOnEvent($tabMain, "tabMain")
GUICtrlSetOnEvent($btnStart, "btnStart")
GUICtrlSetOnEvent($btnStop, "btnStop")
GUICtrlSetOnEvent($btnPause, "btnPause")
GUICtrlSetOnEvent($btnHide, "btnHide")
GUICtrlSetOnEvent($chkBackground, "chkBackground")
GUICtrlSetOnEvent($chkForceBS, "chkForceBS")
GUICtrlSetOnEvent($btnAtkNow, "btnAtkNow")
GUICtrlSetOnEvent($btnLocateTownHall, "btnLocateTownHall")
GUICtrlSetOnEvent($btnLocateClanCastle2, "btnLocateClanCastle")
GUICtrlSetOnEvent($btnLocateKingAltar, "btnLocateKingAltar")
GUICtrlSetOnEvent($btnLocateQueenAltar, "btnLocateQueenAltar")
GUICtrlSetOnEvent($btnLocateDarkBarracks, "btnLocateDarkBarracks")
GUICtrlSetOnEvent($btnLocateBarracks, "btnLocateBarracks")
GUICtrlSetOnEvent($btnLocateSFactory, "btnLocateSFactory")
GUICtrlSetOnEvent($btnLocateCamp, "btnLocateCamp")
GUICtrlSetOnEvent($chkNoAttack, "chkNoAttack")
GUICtrlSetOnEvent($chkDonateOnly, "chkNoAttack")
GUICtrlSetOnEvent($btnSearchMode, "btnSearchMode")
GUICtrlSetOnEvent($chkRandomSpeedAtk_vip, "Randomspeedatk")
GUICtrlSetOnEvent($btnFindWall_vip, "btnFindWall")
GUICtrlSetOnEvent($btnLocateUp1_vip, "btnLocateUp1")
GUICtrlSetOnEvent($btnLocateUp2_vip, "btnLocateUp2")
GUICtrlSetOnEvent($btnLocateUp3_vip, "btnLocateUp3")
GUICtrlSetOnEvent($btnCheckDefense, "btnCheckDefense")
GUICtrlSetOnEvent($chkPushMatchFound_vip, "MatchFound")

; add vip features to array
ReDim $vipControls[59] ; define number of elements for array
$vipControls[0] = $cmbUnitDelay_vip
$vipControls[1] = $cmbWaveDelay_vip
$vipControls[2] = $chkRandomSpeedAtk_vip
$vipControls[3] = $chkRedLine_vip
$vipControls[4] = $chkWalls_vip
$vipControls[5] = $btnFindWall_vip
$vipControls[6] = $UseGold_vip
$vipControls[7] = $UseElixir_vip
$vipControls[8] = $UseGoldElix_vip
$vipControls[9] = $cmbWalls_vip
$vipControls[10] = $cmbTolerance_vip
$vipControls[11] = $txtWallMinGold_vip
$vipControls[12] = $txtWallMinElixir_vip
$vipControls[13] = $chkUpgrade1_vip
$vipControls[14] = $chkUpgrade2_vip
$vipControls[15] = $chkUpgrade3_vip
$vipControls[16] = $txtUpgradeX1_vip
$vipControls[17] = $txtUpgradeX2_vip
$vipControls[18] = $txtUpgradeX3_vip
$vipControls[19] = $txtUpgradeY1_vip
$vipControls[20] = $txtUpgradeY2_vip
$vipControls[21] = $txtUpgradeY3_vip
$vipControls[22] = $btnLocateUp1_vip
$vipControls[23] = $btnLocateUp2_vip
$vipControls[24] = $btnLocateUp3_vip
$vipControls[25] = $txtBldgMinGold_vip
$vipControls[26] = $txtBldgMinElixir_vip
#cs
$vipControls[27] = $cmbBoostBarracks_vip
$vipControls[28] = $chkBoostKing_vip
$vipControls[29] = $chkBoostQueen_vip
$vipControls[30] = $chkBoostRax1_vip
$vipControls[31] = $chkBoostRax2_vip
$vipControls[32] = $chkBoostRax3_vip
$vipControls[33] = $chkBoostRax4_vip
$vipControls[34] = $chkBoostDark1_vip
$vipControls[35] = $chkBoostDark2_vip
$vipControls[36] = $chkBoostSpell_vip
#ce
$vipControls[37] = $cmbDeadAttackTH_vip
$vipControls[38] = $cmbAttackTH_vip
$vipControls[39] = $chkSpellDarkStorage_vip
$vipControls[40] = $txtSpellDarkStorage_vip
$vipControls[41] = $chkMultiLight_vip
$vipControls[42] = $chkPushBulletEnabled_vip
$vipControls[43] = $chkPushBulletDebug_vip
$vipControls[44] = $chkPushBulletRemote_vip
$vipControls[45] = $chkPushBulletDelete_vip
$vipControls[46] = $txtPushBulletTokenValue_vip
$vipControls[47] = $chkPushVillageReport_vip
$vipControls[48] = $chkPushMatchFound_vip
$vipControls[49] = $chkPushLastRaid_vip
$vipControls[50] = $chkPushTotalRaid_vip
$vipControls[51] = $chkPushFreeBuilder_vip
$vipControls[52] = $chkPushError_vip
$vipControls[53] = $UsePushJPG_vip
$vipControls[54] = $UsePushText_vip
$vipControls[55] = $cmbPushDevice_vip
$vipControls[56] = $txtPushBulletInterval_vip
$vipControls[57] = $txtPushBulletMessages_vip
$vipControls[58] = $UseSkillAuto_vip

; set title and icons
WinSetTitle("sBotTitle", "", $sBotTitle)
GUISetIcon(@ScriptDir & "Images\Icons\cocbot.ico")
TraySetIcon(@ScriptDir & "Images\Icons\cocbot.ico")

; add log text box
$txtLog = _GUICtrlRichEdit_Create($frmBot, "", 8, 68, 480, 185, BitOR($ES_MULTILINE, $ES_READONLY, $WS_VSCROLL, 8912))

; Add Banner
$hPic_background = GUICtrlCreatePic(@ScriptDir & "\images\GUI\bannerfix.bmp", 0, 0, 640, 30)
GUICtrlSetState($hPic_background, $GUI_DISABLE)

;Bottom status bar
$statLog = _GUICtrlStatusBar_Create($frmBot)
_GUICtrlStatusBar_SetSimple($statLog)
_GUICtrlStatusBar_SetText($statLog, "Status : Idle")
$tiAbout = TrayCreateItem("About")
TrayCreateItem("")
$tiExit = TrayCreateItem("Exit")

; Display Form
GUISetState(@SW_SHOW, $frmBot)
